### ISSUE TITLE
Bandwidth and Compute Resource Overlay

### ISSUE THREAD

**Issue by kasmtech** [kasmtech/KasmVNC#1]
It is difficult to troubleshoot bandwidth issues versus compute contention issues as they look similar to the user. This is especially an issue when you have a single large central installation with hundreds of users. We should look into using existing mechanisms in the code base for measuring bandwidth issues. We should also find a way to measure compute resources. Optimally, this compute resource measurement should not use system tools but rather calculate based on the time it is taking to encode perhaps. The user should be able to turn this tracking on and it would be sent to the client which would overlay the data on the screen.

**Comment by kasmtech** [comment]
@clbr, I've pushed the UI changes to the stats branch. The CPU always seem to be right at 10/10, even when the Xvnc process is at 100% CPU utilization. Can you explain what the total field is? It appears to stick to the lowest value during measurement, which is fine, just want to be sure I understand what it is. Can we change the returned data to json, such as [ 9.7, 9.4, 8.2, 6.9 ], where the values are: cpu recent, cpu total, network recent, network total. Right now we will just display text but at some point we may want to display a graph over time, so json data would be best.

**Comment by clbr** [comment]
Recent is during the last minute, total is during the lifetime of this client's connection.

I suppose we could print the encoding times each frame on the maximum debug logging, but it'll be a lot of output, one line per frame. JSON, ok.

**Comment by kasmtech** [comment]
That would probably be too much output. Perhaps keep a rolling max delay over the last n frames. I do like the current statistic output, just need to find a way to tune it. I have not done thorough testing yet, but the network stats do seem to fluctuate well with activity. I will use tc to inject network delay and restrict bandwidth to test further.

**Comment by clbr** [comment]
The current cpu formula is:
- encoding took too long is worth 1 frame points
- almost took too long, within 20% of the edge; worth 0.2 points
Then the sum is divided by the frames sent, scaled to the 10 range, and inverted. If half the frames took too long, it should show 5/10. If all frames are quick enough but close to the edge, it would show 8/10.

**Comment by kasmtech** [comment]
That sounds like a good strategy. I think we just need some tweaking. The only time I can get the CPU to budge from 10/10 is when playing video. I'll send you a screenshot. You will see the VM is pegged on both cores. Video frame rate is horrible, xnvc clearly cannot keep up but the rating is 9.6/10. Note the large amount of 'S' in nmon, that is steal. This is a low end VM in GCP with a shared CPU. You get 100% of both cores up to a point, after which you get 33% of each core. Playing video causes the VM to trigger into that 33% mode in which case 66% shows up as 'S' in nmon.

**Comment by clbr** [comment]
Pushed the JSON array format and the debug log print. Please see what it prints on your VM (needs the maximum log level of 100).

**Comment by kasmtech** [comment]
When I start a video, Terminator 2 (very important), the frame rate is really good. After about 20 seconds the CPU burst mode ends and it is limited to 30% on each core, the frame rate immediately drops. You can see that the network rating did not drop but the encode time went up by an order of magnitude. While I understand 231ms to encode 30 frames still seems adequate, I am witnessing a really bad drop in frame rate and it is very clearly caused by CPU resource contention. Perhaps there is more processing going on that is not included in encode time.

 EncodeManager: Max encoding time during the last 30 frames: 27 ms (limit 33, near limit 26)
 EncodeManager: Max encoding time during the last 30 frames: 59 ms (limit 33, near limit 26)
 EncodeManager: Max encoding time during the last 30 frames: 11 ms (limit 33, near limit 26)
 EncodeManager: Max encoding time during the last 30 frames: 37 ms (limit 33, near limit 26) **<--- CPU Burst Mode**
 VNCSConnST:  Sending client stats:
[ 9.7, 9.8, 3.3, 6.7 ]

 VNCSConnST:  Sending client stats:
[ 9.7, 9.8, 3.4, 6.7 ]

 EncodeManager: Max encoding time during the last 30 frames: 231 ms (limit 33, near limit 26) **<-- CPU Capped at 30%**
 VNCSConnST:  Sending client stats:
[ 9.8, 9.8, 3.4, 6.7 ]

 VNCSConnST:  Sending client stats:
[ 9.7, 9.8, 3.5, 6.6 ]

**Comment by clbr** [comment]
231ms is the max delay, not the sum. So that longest frame took 7 frames' worth.

The log file says the stat does adapt, but slowly; I've pushed a commit to make it adapt faster. A straight average over the last minute won't show immediate effects if a couple seconds have jitter, but now it's changed to give recent delays more weight.

**Comment by kasmtech** [comment]
with the latest commit, I get a 401 on authentication. I've tried setting the password using kasmvncpasswd and through the commandline argument. Here are the logs on the serverside...

139810656192256:error:14094416:SSL routines:ssl3_read_bytes:sslv3 alert certificate unknown:../ssl/record/rec_layer_s3.c:1528:SSL alert number 46
 websocket 29: using SSL socket
 websocket 29: Client closed during handshake
 websocket 29: No connection after handshake
 websocket 29: handler exit
139810647799552:error:14094416:SSL routines:ssl3_read_bytes:sslv3 alert certificate unknown:../ssl/record/rec_layer_s3.c:1528:SSL alert number 46
 websocket 30: using SSL socket
 websocket 30: Client closed during handshake
 websocket 30: No connection after handshake
 websocket 30: handler exit
 websocket 31: got client connection from 73.147.179.230
 websocket 32: got client connection from 73.147.179.230
139810639406848:error:14094416:SSL routines:ssl3_read_bytes:sslv3 alert certificate unknown:../ssl/record/rec_layer_s3.c:1528:SSL alert number 46
 websocket 31: using SSL socket
 websocket 31: Client closed during handshake
 websocket 31: No connection after handshake
 websocket 31: handler exit
139810631014144:error:14094416:SSL routines:ssl3_read_bytes:sslv3 alert certificate unknown:../ssl/record/rec_layer_s3.c:1528:SSL alert number 46
 websocket 32: using SSL socket
 websocket 32: Client closed during handshake
 websocket 32: No connection after handshake
 websocket 32: handler exit

**Comment by clbr** [comment]
Not easily. In theory it shouldn't affect it already, but the network code is a bit complex.

**Comment by clbr** [comment]
Should we use a smaller "recent" value than one minute? 10s?

**Comment by kasmtech** [comment]
Yes, I think that would help. If there was a variable I could tune to adjust the recent timing that would be great, does not have to be exposed as a setting, I would just like to be able to tweak that with a recompile at least. Eventually I will make a graph overlay that will track over time, so I suspect I will want to lower it more then. Right now I’m displaying a single value, so 10s is probably better for that.

**Comment by clbr** [comment]
Logging and the recentSecs = 10 change pushed.
