### ISSUE TITLE
Support for Ubuntu Jammy (22.04 LTS)

### ISSUE THREAD

**Issue by Justsnoopy30** [kasmtech/KasmVNC#100]
There is no package available for jammy, and attempting to install the focal package fails due to the absence of `libnettle7`:

```
$ sudo apt install ./kasmvncserver_ubuntu_focal_0.9.2_amd64.deb 
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
Note, selecting 'kasmvncserver' instead of './kasmvncserver_ubuntu_focal_0.9.2_amd64.deb'
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 kasmvncserver : Depends: libnettle7 but it is not installable
E: Unable to correct problems, you have held broken packages.
```

**Comment by mmcclaskey** [comment]
Hello, I have put in a ticket internally to add build support for jammy. Hopefully we will get it in the next release due within the next 30 to 45 days.

**Comment by ledestin** [comment]
@Justsnoopy30 Jammy packages were release as part of 0.9.3 release.
https://github.com/kasmtech/KasmVNC/releases/download/untagged-f566a3bf2b0dea1545c7/kasmvncserver_jammy_0.9.3_amd64.deb

**Comment by zalo** [comment]
> @Justsnoopy30 Jammy packages were release as part of 0.9.3 release. https://github.com/kasmtech/KasmVNC/releases/download/untagged-f566a3bf2b0dea1545c7/kasmvncserver_jammy_0.9.3_amd64.deb

Hi @ledestin , it doesn't look like we can see that release.  Is it publicly accessible?

**Comment by ledestin** [comment]
Hi @zalo. Not sure what happened, I made sure this link works without me being logged in:
https://github.com/kasmtech/KasmVNC/releases/download/v0.9.3-beta/kasmvncserver_jammy_0.9.3_amd64.deb

**Comment by mmcclaskey** [comment]
Jammy is officially supported on the latest release.
