### ISSUE TITLE
is kasmvnc  memory leak?

### ISSUE THREAD

**Issue by queguan** [kasmtech/KasmVNC#101]
hello ,
    I used kasmVnc  in images.  The version is 0.9.1~beta-1+libjpeg-turbo-latest. I found that as the running time becomes longer, the memory will be more and more, the maximum can reach 6G.Finally reboot to free up memory.   is kasmvnc memory leak ?
    thanks for reply.

**Comment by queguan** [comment]
![ajt](https://user-images.githubusercontent.com/23637152/173560185-7e5b320d-a060-43b9-8458-48714654c1d8.png)

**Comment by queguan** [comment]
Thank you for reply.
I used https://github.com/kasmtech/workspaces-core-images/blob/release/1.10.0/dockerfile-kasm-core to   build a base images.  Additionally installed chrome and vscode, edit vnc_startup.sh canceled ssl. when I in desktop of k8s pod used chrome access foxglove studio，the memory increase rapidly.  Can you give me some help or advice?
![image](https://user-images.githubusercontent.com/23637152/173570064-773eb888-2a54-4825-a50b-30b628edb525.png)

**Comment by queguan** [comment]
I run the base images as a container ,  Quick refresh  chrome  several times，It can also be found that the  memory of xvnc has increased significantly

https://user-images.githubusercontent.com/23637152/173575088-8c048452-95a3-49be-9d5f-ea58b9edcf95.mp4

.

**Comment by mmcclaskey** [comment]
This was fixed with release 0.9.3
https://github.com/kasmtech/KasmVNC/commit/924329900dd6942a3336992ad7534a640c7e264d
