### ISSUE TITLE
Cannot build master branch - no package.json

### ISSUE THREAD

**Issue by JaktensTid** [kasmtech/KasmVNC#112]
I am trying to build master branch on ubuntu focal using this command

sudo builder/build-package ubuntu focal

I get an error on build
`Step 5/6 : RUN npm install
 ---> Running in 0e8b17c32e00
npm WARN saveError ENOENT: no such file or directory, open '/src/www/package.json'
npm notice created a lockfile as package-lock.json. You should commit this file.
npm WARN enoent ENOENT: no such file or directory, open '/src/www/package.json'
npm WARN www No description
npm WARN www No repository field.
npm WARN www No README data
npm WARN www No license field.

up to date in 1.052s
found 0 vulnerabilities

Removing intermediate container 0e8b17c32e00
 ---> 5608b0540418
Step 6/6 : ENTRYPOINT [ "/src/build_www.sh" ]
 ---> Running in 88c42bbbf1b4
Removing intermediate container 88c42bbbf1b4
 ---> 8787e7c88c1a
Successfully built 8787e7c88c1a
Successfully tagged kasmweb/www:latest
npm ERR! code ENOENT
npm ERR! syscall open
npm ERR! path /src/www/package.json
npm ERR! errno -2
npm ERR! enoent ENOENT: no such file or directory, open '/src/www/package.json'
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2022-11-15T20_14_16_232Z-debug.log
rm: cannot remove '*.md': No such file or directory
rm: cannot remove 'AUTHORS': No such file or directory
rm: cannot remove 'vnc.html': No such file or directory`

**Comment by misolietavec** [comment]
Try to execute the builder command second time. This helps me with build for debian bullseye.

**Comment by mmcclaskey** [comment]
Are you building this on ARM by chance?

**Comment by mmcclaskey** [comment]
Closing due to lack of response, feel free to reopen if you have additional information. 

The build process does not support building the web code on ARM. So you have to build the www code on x86 then move the resulting www build to the arm platform for build. See our Gitlab pipeline definition file .gitlab-ci.yaml to see how we build things in multiple stages, with the www code building first on one stage and then reused by all subsequent stages so we aren't building the same www code for every single platform and architecture.

**Comment by JaktensTid** [comment]
No, I was building x64 ubuntu

**Comment by JaktensTid** [comment]
@misolietavec when I execute command second time http server for kasmvnc is not being build and I end up with just empty http server directory

**Comment by misolietavec** [comment]
Did you clone with submodules?

git clone --recurse-submodules https://github.com/kasmtech/KasmVNC.git

**Comment by JaktensTid** [comment]
@misolietavec good point... let me try
