### ISSUE TITLE
HTTP Basic Auth is not required is there any parameter to control it?

### ISSUE THREAD

**Issue by LH667371** [kasmtech/KasmVNC#114]
HTTP Basic Auth is not required is there any parameter to control it?

**Comment by mmcclaskey** [comment]
https://github.com/kasmtech/KasmVNC/blob/39f6ee7691d58bb4c6fadcbc0fd8e870189571f7/unix/xserver/hw/vnc/Xvnc.man#L370

**Comment by LH667371** [comment]
> https://github.com/kasmtech/KasmVNC/blob/39f6ee7691d58bb4c6fadcbc0fd8e870189571f7/unix/xserver/hw/vnc/Xvnc.man#L370

This is very useful, thanks a lot!
