### ISSUE TITLE
How to Connect via VNC

### ISSUE THREAD

**Issue by ZelleAP** [kasmtech/KasmVNC#119]
I know the use is via websocket but I would like also have the possibility to connect via VNC Client with e.g. 5900 default port.
Could someone help me, how to configure that?!

**Comment by mmcclaskey** [comment]
While you can technically still enable the TCP VNC port, KasmVNC does not follow the RFB specification anymore. We had to break it in a few places in order to add features. For that reason, KasmVNC will not work with legacy VNC clients.
