### ISSUE TITLE
KasmVNC with no interactive authentication

### ISSUE THREAD

**Issue by paulieguk** [kasmtech/KasmVNC#120]
Hi,
We are looking to use the Kali core image which also uses the KasmVNC.  The platform we want to run it on provides all the authentication services we need and allows us to dynamically geo-load balance around the world.  So we are trying to run the Kali Core container without the Basic Auth request from KasmVNC.  Is that possible are there some environment variables we could set and pass or some commands we can run on container startup to remove this requirement?

The core issue for us is we spin the containers up behind a NGINX running as a reverse proxy.  Really appreciate any ideas.  Many thanks.

**Comment by mmcclaskey** [comment]
@paulieguk , there are two options. The first option is to have NGINX inject the authorization header. You can do that with a static add_header directive. The second option is to just disable authentication in KasmVNC, however, this is insecure, so I would highly recommend not doing this. Another reason that I would not recommend this option, is that it is not a supported configuration in the YAML config file, however, you can still pass commandline arguments to vncserver and they will override the yaml config file settings where applicable. The argument is -disableBasicAuth.

https://github.com/kasmtech/KasmVNC/blob/95f64ce1f29bb7a08d8b97b36375d10653bd3825/unix/xserver/hw/vnc/Xvnc.man#L370
