### ISSUE TITLE
Auto login

### ISSUE THREAD

**Issue by mmolaie** [kasmtech/KasmVNC#124]
is there anyway to autologin to kasmvnc for basic auth?  example to pass the user/pass in url  or anything other 
Dont want user pass the login manually
tnx

**Comment by mmcclaskey** [comment]
You could place a proxy in front of KasmVNC, such as nginx, and have nginx inject the basic authorization header. The username and password are base64 encoded. Search google and you should be able to find examples of such a configuration. 

You could also disable basic auth in KasmVNC. In both scenarios you are disabling authentication essentially, so you would be responsbile for ensuring the security of it some how.

**Comment by VaalaCat** [comment]
@mmcclaskey Not seen any instruction of disable disable basic auth, wonder if there any doc/wiki shows the way how

**Comment by VaalaCat** [comment]
This repo helps: https://github.com/bpmct/coder-templates/blob/main/better-vnc/build/vnc_startup.sh#L65

**Comment by mmolaie** [comment]
Actually want to use some thing like Password option to have simple auth like this
test.local?password=123
Could you please discribe how can I do this?

I tried the next but said **Unrecognized option: -Password**
 vncserver -DisableBasicAuth -Password 123

**Comment by mmcclaskey** [comment]
To disable basic auth pass -disableBasicAuth

https://github.com/kasmtech/KasmVNC/blob/6228dd1fe479bda3a2947d769509c5c8b5b28b6f/unix/xserver/hw/vnc/Xvnc.man#L370

This option is not supported by our yaml based configuration, however, vncserver will still pass CLI arguments to Xvnc. 

There is no -Password option. KasmVNC currently only supports Basic auth, that may change, but for now, if you wanted to implement your own authentication, you would need to put a proxy in front of KasmVNC and have the proxy enforce security and pass basic auth to KasmVNC if your authentication implementation passed.
