### ISSUE TITLE
Building a deb package for Ubuntu 18

### ISSUE THREAD

**Issue by ledestin** [kasmtech/KasmVNC#13]
Hi,

I'm in the process of making a deb for Ubuntu 18. Here are my notes, based on `kasmvnc-Linux-x86_64-0.9.tar.gz` that Docker build made:
- swrast_dri.so is in libgl1-mesa-dri, but bundled in the tar. No binaries in /usr/local/bin/ even depend on it. Should I just ditch it? If it's used by Xorg is it really needed? It'll conflict with other packages that have it and will need to be resolved in some way.
- man1/Xserver.1 should be included in the distro. I'm ditching it.
- vncserver(1), vncpasswd(1), etc. The other packages use naming like this:
    - /usr/bin/tigervncserver
    - /usr/bin/tightvncserver
    - Would you like to convert to a similar scheme? kasmvncserver?
- There's a virtual package of vnc-server, and KasmVNC will be one of the alternatives.

If you create any files while the vnc server runs, where do they go?

**Comment by kasmtech** [comment]
- I would say ditch swrast_dri.so if it is not used. We will find out pretty quickly if removing it is an issue.
- There is already a kasmvncpasswd. If there is still a vncpasswd in the build it is likely not needed. Lets try renaming vncserver to kasmvncserver, it should be fine, its just a perl script.
- There are some files that are created by the vncserver perl script and they all go in $HOME/.vnc

**Comment by ledestin** [comment]
Thanks, Matt.

I've done some research today and found out that:
* Lots of Debian packages are used in Ubuntu unchanged.
* Ubuntu-native packages use Bazaar CVS, which would be an initial learning curve and maintenance later.

Because of the reasons above, I decided to create a Debian source package, which can be compiled for both Ubuntu and Debian.

I was trying to determine whether it makes sense to go with the standard approach to packaging or the one I used. The standard way uses a source tar and I just clone repo and don't apply any patches. I think I'll use the standard approach. because that's what Debian would expect, and I don't know whether you can easily switch between the formats. Well, I'll just clone from Github and create a tar. This way there should be no surprises.

**Comment by kasmtech** [comment]
I just added a new branch, https://github.com/kasmtech/KasmVNC/tree/feature/12_ubuntu_20, which adds new docker images for debian 10 and ubuntu 20.04. Ubuntu 20 compiles but has runtime issues. Debian is compiling as I write this, I ran out of time. But, you can see from this how we can compile for different OSes. Each OS has two docker images, a build and test one. The build one has an environmental variable called "XORG_VER" at the top of the dockerfile. This is used during the build process to download the appropriate version of xorg and apply the correct patch. Otherwise they are nearly identical. Each build results in a tar file. The README has been updated showing how to build and test a build. I started on CentOS, did not get a chance to even try compiling yet.

**Comment by kasmtech** [comment]
Debian 10 does compile but on runtime gets the following error. 

/usr/local/bin/Xvnc: error while loading shared libraries: libjpeg.so.62: cannot open shared object file: No such file or directory

**Comment by ledestin** [comment]
There's no `libjpeg8` in Debian Buster. People suggest using `libjpeg62-turbo`. I do have libjpeg8 on my system as part of Steam though, which installs lots of stuff in `~/.local`.

I've managed to create a source package, and the next step is to try building it inside Docker. I'm doing it step by step, so it'll include only binaries first. I'm taking an approach to use generated tarball as the file source. I'll see how I can improve the build process by possibly putting dependencies into the package control file, that way it wouldn't need to be repeated in Docker files.

As for PPA, having just a repo for Debian/Ubuntu as Spotify does would be less effort to make. At least for now.

**Comment by ledestin** [comment]
Made a binary package inside Docker, fiddled with testing it. I'm not sure if it'll pick up `/usr/share/kasmvnc/www`, and not in `/usr/local/share`. I need to test whether the tarball version of test works first, took too big of a step to testing .deb.

**Comment by ledestin** [comment]
I've improved the binary package today and tried testing it on a fresh Ubuntu 18.04 image. There are some issues Lintian found:
* Xvnc.1 is empty. It's supposed by be the manual page for Xkasmvnc.
*  At his point, the following is not a problem, but may be if you want to get into Debian.:
   "This package appears to be covered by the GNU GPL but depends on the OpenSSL libssl package and does not mention a license exemption or exception for OpenSSL in its copyright file. The GPL (including version 3) is incompatible with some terms of the OpenSSL license, and therefore Debian does not allow GPL-licensed code linked with OpenSSL libraries unless there is a license exception explicitly permitting this."
  https://lintian.debian.org/tags/possible-gpl-code-linked-with-openssl.html

* Node scripts. The test image has no Nodejs installed, so maybe these shouldn't be included in the package:
E: kasmvncserver: missing-dep-for-interpreter node => nodejs (usr/share/kasmvnc/www/po/po2js) #!node
E: kasmvncserver: missing-dep-for-interpreter node => nodejs (usr/share/kasmvnc/www/po/xgettext-html) #!node
* Minor warnings:
W: kasmvncserver: script-not-executable usr/share/kasmvnc/www/utils/genkeysymdef.js
W: kasmvncserver: script-not-executable usr/share/kasmvnc/www/utils/use_require.js

Also, I have a question. What vncpasswd is for, when there's kasmvncpasswd?

I'll continue to test the package tomorrow.

**Comment by ledestin** [comment]
Setup KasmVNC binaries as alternatives for `vncserver`, etc today. I've set priority to 90, which is higher than tigervnc. It means that auto-selection will favour KasmVNC. I did for easier testing, it's up to you how high you want to set it.

Certificate could be auto-generated automatically for all users on install. Then the certificate could be allowed to read by a group, users would just need to be added to the group. It's a common practice. Would you like that?

**Comment by kasmtech** [comment]
@ledestin, sorry on vacation. I would agree on your proposal for the user cert. I would also agree what you have recommended for the auto-selection priority. To give you some background.... We use this on our larger Kasm VDI solution, but want to make it useful for the open source community as well. We don't really need what you are working on for our larger VDI solution, it is almost entirely for the benefit of the open source community. We do want KasmVNC to become popular and the new default VNC for many distros... some day. 

vncpasswd is likely no longer used. 

I'm not sure why those nodejs packages exists. I would say filter them out on the build if they are not needed. 

I will create a ticket on the OpenSSL issue so we don't lose track of it.

I'll have our primary C++ contributor look into your comments as well.

**Comment by ledestin** [comment]
Thanks for explaining, Matt.

* I've added certificate generation on package install.
* Firefox complains about TLS not being 1.2. They will remove non-1.2 support in the future.
* Tried testing .deb, and I get an empty response from the web server. Logs don't say anything useful.

I'll work on automating package building chain next. Right now I'm using 2 docker containers for dev and testing .deb, and there's some manual work involved.

**Comment by ledestin** [comment]
I've tried running vncserver from a .deb install and got this:
```
websocket 150: got client connection from 172.17.0.1
 EncodeManager: WEBP benchmark result: 14 ms
 Connections: accepted: websocket
 SConnection: Client needs protocol version 3.8
 SConnection: Client requests security type VncAuth(2)
 SConnection: AuthFailureException: Authentication failure
 Connections: closed: websocket (Authentication failure)
 EncodeManager: Framebuffer updates: 0
 EncodeManager:   Total: 0 rects, 0 pixels
 EncodeManager:          0 B (1:-nan ratio)
 ComparingUpdateTracker: 0 pixels in / 0 pixels out
 ComparingUpdateTracker: (1:-nan ratio)
```

Do you have any idea what's wrong? I've got vnc.html loaded, but I can't get past the "Connect" button.

I have a draft package building chain working in `create_ubuntu_packages` branch. Don't mind the code, it's a draft and only works for Ubuntu 18 for now.
You should be able to build a .deb and run a test with this:
```
builder/build-tarball
builder/build-deb
builder/test-deb
```

**Comment by ledestin** [comment]
To be included in the **official** Debian, a lot of changes would need to be made:
* All dependencies must be satisfied by Debian packages. I.e. xorg, libwebp can't be downloaded. Would have to patch Xorg that's included in Debian/Ubuntu. "You need to build without network access (after build-deps are fetched)".
* Debian has libwebp6, I was suggested updating that package to a new version (v1). The easiest option is that the maintainer would update it, the hardest is that I'd have to update it myself.
* Can't use `apt-get build-dep` or `apt-get install` to get dependencies, all dependencies must be listed in the package source.
* Other changes that would make the build process standard Debian, like having deb-specific patches.
* The Debian lifecycle is that new packages go into unstable, and then propagate from there. There are backports, but it's more work again.

So, there are lots of changes down that road. Upsides would be:
* Possible free ride to Ubuntu releases (tigervnc is in Ubuntu, after all).
* Standard way of building .deb, no learning curve for people that want to work on it.

Do you want to go down that road?

**Comment by kasmtech** [comment]
Sorry for the delay, testing now. I've ran into a few issues caused by permissions. The build-tarball script creates a folder build, however, the docker container is running as user 'docker' which does not have permissions to that folder. So the last step in the build.sh is to copy the tarball to that directory and that step fails. I got around that by chmod 777 build, and reran the script. I did not have these issues before because it was mapped to /tmp. I remember being lazy and not wanting to deal with the permissions issues. The easy solution is map /tmp from host to /build inside the container and then the final step of build-tarball would be to copy from /tmp to build/ and change the permissions if needed. 

The build-deb uses a docker image built to run with user 1000. Since my userID is not 1000, there are permissions issues. To fix this I modified the build-deb script, it should be ran directly without sudo.

```
#!/bin/bash

set -e

cd "$(dirname "$0")/.."

sudo docker build -t debbuilder_ubuntu:18.04 -f \
  builder/dockerfile.ubuntu1804.deb.build .

deb_output_dir=$(cd .. && echo $PWD)
L_UID=$(id -u) #Ubuntu already has UID env var, but this should work on all Linix systems
L_GID=$(id -g)
sudo docker run --rm -v "$deb_output_dir":/src --user $L_UID:$L_GID debbuilder_ubuntu:18.04 /bin/bash -c '/src/*/builder/build-deb-inside-docker'
```

**Comment by kasmtech** [comment]
@ledestin, lets not go down that road just yet. Lets make the deb packages professional and usable by end users and in our own ppa. Lets continue on to other operating systems and circle back to getting to the Debian repo later.

**Comment by ledestin** [comment]
Thanks for the fixes!

On dangers of using /tmp with predictable file paths:
https://security.stackexchange.com/questions/34397/how-can-an-attacker-use-a-fake-temp-file-to-compromise-a-program
I'll change it to use a random directory name.

How do automated builds work with sudo? You'd need to enter a password.

**Comment by kasmtech** [comment]
Good call, you can remove the sudo. Instead, we should just add our user to the docker group so we can run docker commands without sudo. In a CI pipeline, it will be able to run docker commands without sudo, so it should work there as well as our local systems.

**Comment by clbr** [comment]
Note about TLS 1.2, that support is present on the users branch, which will be merged in the future.

**Comment by ledestin** [comment]
@clbr I've checked, and Debian Buster uses xorg 1.20.4. Last December, the package was updated with a security fix. Since the version stayed the same, I conclude that xorg was patched.

But we use old xorg version, right? Wouldn't it open KasmVNC to security vulnerabilities?

**Comment by clbr** [comment]
I think the official package uses 1.19, but it compiles against many xorg versions, including 1.20.

Yes, building against 1.19 may open it to vulns, but X listening to local apps only by default means the user has to run EvilApp on the kasm desktop.

**Comment by kasmtech** [comment]
@ledestin , @clbr , Please correct me if I am wrong, but you can compile KasmVNC using 1.19 or 1.20. Please look at the following build.sh on a branch I never merged in. It adds an optional environmental variables to the build process, XORG_VER which defaults to 1.19.6. If you set the env variable to 1.20.4 it will download that version and patch using the correct patch for that version. I did this in an attempt to compile for Ubuntu 20. @ledestin , if this looks good you may want to incorporate this into your branch and set XORG_VER in each respective dockerfile to match the target OS.

https://github.com/kasmtech/KasmVNC/blob/feature/12_ubuntu_20/builder/build.sh

**Comment by ledestin** [comment]
@kasmtech it should be possible. I don't know how Xorg releases its stuff, but potentially, getting a release with all vulnerabilities fixed would work. I guess even 1.20 would be patched and 1.20.1 would be released, and would need to use that.

**Comment by ledestin** [comment]
@clbr Thanks for adding `-key`, that helped a lot.

I started getting packages generated with debug symbols for some reason. Here are the contents of such package:
```
$dpkg -c builder/build/debian_10/kasmvncserver-dbgsym_0.9.1~beta-1_amd64.deb 
drwxr-xr-x root/root         0 2020-12-25 21:29 ./
drwxr-xr-x root/root         0 2020-12-25 21:29 ./usr/
drwxr-xr-x root/root         0 2020-12-25 21:29 ./usr/lib/
drwxr-xr-x root/root         0 2020-12-25 21:29 ./usr/lib/debug/
drwxr-xr-x root/root         0 2020-12-25 21:29 ./usr/lib/debug/.build-id/
drwxr-xr-x root/root         0 2020-12-25 21:29 ./usr/lib/debug/.build-id/52/
-rw-r--r-- root/root   6753664 2020-12-25 21:29 ./usr/lib/debug/.build-id/52/2383f5bfd3627c9f40def02c0999a40c77315f.debug
drwxr-xr-x root/root         0 2020-12-25 21:29 ./usr/lib/debug/.build-id/74/
-rw-r--r-- root/root      6368 2020-12-25 21:29 ./usr/lib/debug/.build-id/74/7aa9c191480e8baa4cd29fc5280843e61ab066.debug
drwxr-xr-x root/root         0 2020-12-25 21:29 ./usr/lib/debug/.build-id/7a/
-rw-r--r-- root/root     38728 2020-12-25 21:29 ./usr/lib/debug/.build-id/7a/d82fb58d3ea734c699a8c158712464abc64832.debug
drwxr-xr-x root/root         0 2020-12-25 21:29 ./usr/share/
drwxr-xr-x root/root         0 2020-12-25 21:29 ./usr/share/doc/
lrwxrwxrwx root/root         0 2020-12-25 21:29 ./usr/share/doc/kasmvncserver-dbgsym -> kasmvncserver
```

Does it ring any bells?

**Comment by clbr** [comment]
That's something debian-specific I guess, I don't see such (I do native builds).

**Comment by ledestin** [comment]
@kasmtech do you want to provide debug symbol packages? They're supposed to be generated automatically, and they are, but there's a problem. The package generated has files, but they don't have debug symbols.

Lintian docs:
```
The binary is installed as a detached "debug symbols" ELF file, but it does not appear to have debug information associated with it.

A common cause is not passing -g to GCC when compiling.

Implementation detail: Lintian checks for the ".debug_line" and the ".debug_str" sections. If either of these are present, the binary is assumed to contain debug information.
```

**Comment by mmcclaskey** [comment]
As the document suggests, I believe you have to compile it in a way to
include debug symbols and I don't think that is normal for a production
release. Can we just remove the debug files after the build?

**Comment by ledestin** [comment]
@mmcclaskey @clbr I've used `-D CMAKE_BUILD_TYPE=RelWithDebInfo` and it solved the problem. Debian package building machinery strips debug symbols and makes a separate package for them.
