### ISSUE TITLE
KasmVNC on Debian 11 "bullseye", how to install? 

### ISSUE THREAD

**Issue by avscta** [kasmtech/KasmVNC#138]
**Description**
I would like to know which asset I should try for installing it on a Debian 11 "bullseye" OS (if supported at all)?

**System Description**
SMP Debian 5.10.70-1 (2021-09-30) x86_64 GNU/Linux

**Comment by mmcclaskey** [comment]
The latest release has been updated with deb packages for Debian Bullseye and Buster

https://github.com/kasmtech/KasmVNC/releases/tag/v1.0.1
