### ISSUE TITLE
Cannot pipe password to kasmvncpasswd

### ISSUE THREAD

**Issue by zacharygraber** [kasmtech/KasmVNC#141]
**Describe the bug**
I need to be able to set up KasmVNC without the need for human intervention (for example, in an Ansible playbook); because of this, I am unable to manually type a password into the `kasmvncpasswd` prompt. When attempting to pass the password through a pipe, I always receive the following message:
```bash
user@hostname:~$ echo -e "test123" | kasmvncpasswd -u user -rwo
getpass error: Inappropriate ioctl for device
```
I am connected via an SSH session--note that physically connecting to the machine is not possible since it is a cloud VM. This behavior persists across an `ssh`, `ssh -t`, and SPICE console session.  

**System Description**
Ubuntu 22.04 LTS virtual machine.
```bash
PRETTY_NAME="Ubuntu 22.04.2 LTS"
NAME="Ubuntu"
VERSION_ID="22.04"
VERSION="22.04.2 LTS (Jammy Jellyfish)"
VERSION_CODENAME=jammy
ID=ubuntu
ID_LIKE=debian
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
UBUNTU_CODENAME=jammy

Linux zeg-kasm-documentation 5.15.0-60-generic #66-Ubuntu SMP Fri Jan 20 14:29:49 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux
```

**KasmVNC Details**
I am using the [1.0.1 GitHub release](https://github.com/kasmtech/KasmVNC/releases/tag/v1.0.1), filename `kasmvncserver_jammy_1.0.1_amd64.deb`

```bash
user@hostname:~$ Xvnc -version

Xvnc KasmVNC 0.9.8285ea812d6433af9504fde6b92e18aac6641e57 - built Dec  1 2022 16:33:10
Copyright (C) 1999-2018 KasmVNC Team and many others (see README.me)
See http://kasmweb.com for information on KasmVNC.
Underlying X server release 12008000, The X.Org Foundation
```

**To Reproduce**
Steps to reproduce the behavior (for non-installation issues):
1. Install the `.deb` package listed above with `sudo apt install -y ./<filename>`
2. Add my user to group: `sudo addgroup user ssl-cert`
3. `logout`
4. `ssh` again
5. Try `echo "test123" | kasmvncpasswd -u user -rwo`

**Expected behavior**
`kasmvncpasswd` should skip the prompt asking for a password and write to the password file.

**Comment by zacharygraber** [comment]
I found issue #23 which seems to be related. That was about a year ago, though, and the build I'm using is much more recent (December). It also references "users branch," which I can't find in the list of branches of this repo.

**Comment by mmcclaskey** [comment]
Here is what we do for our Kasm Workspaces Containers, which use KasmVNC....

https://github.com/kasmtech/workspaces-core-images/blob/2fda3118f00db19834e857397aef30be522102c0/src/common/startup_scripts/vnc_startup.sh#L227

**Comment by clbr** [comment]
Please see the --help output for how to pipe passwords in - the inappropriate ioctl is unrelated (something in your env is confusing isatty, or you were running an older version).

**Comment by ne0YT** [comment]
@zacharygraber I think this can be closed.
