### ISSUE TITLE
GUACAMOLE et KasmVNC

### ISSUE THREAD

**Issue by pnoelfr** [kasmtech/KasmVNC#142]
does this work with guacamole vnc ?

https://guacamole.apache.org/doc/gug/guacamole-architecture.html

**Comment by mmcclaskey** [comment]
Negative. KasmVNC is already web native and does not need a guac server in the middle to translate VNC to HTML5. If you want to have somethign in front of KasmVNC to handle logging, auth, etc, use Kasm Workspaces. In the last release we added the ability for admins to add any server to Kasm Workspaces that has is running an RDP or KasmVNC service.

https://youtu.be/4RLZ1slbX0k

https://www.kasmweb.com/docs/latest/guide/compute/servers.html
