### ISSUE TITLE
Missing man page for Xvnc

### ISSUE THREAD

**Issue by ledestin** [kasmtech/KasmVNC#15]
Tarball contains `/usr/local/man/man1/Xvnc.1`, but it's empty. Since `unix/xserver/hw/vnc/Xvnc.man` exists, it seems like a tarball build issue. Per Debian Policy, programs must have man pages.

**Comment by ledestin** [comment]
@clbr could you please look into it?

**Comment by clbr** [comment]
That's just editing the script to copy it there - I think you can do it? The man page is up to date.

**Comment by ledestin** [comment]
The build system is complicated, so I didn't find the script to amend on the first try. Could you point me in the right direction?

**Comment by clbr** [comment]
builder/build.sh, currently it just touches it to make an empty file.

**Comment by ledestin** [comment]
Fixed in create_fedora_package branch.
