### ISSUE TITLE
Installation on Raspberry Pi 4

### ISSUE THREAD

**Issue by Paranoia8972** [kasmtech/KasmVNC#165]
**Describe the bug**
The issue is that there are unmet dependencies while trying to install the "kasmvncserver" package. Specifically, it requires "libssl1.1" version 1.1.0 or higher, but the package manager is unable to find a compatible version to install. This results in an error message stating that the problem cannot be corrected, and there may be broken packages on your system. And ignoring this doesn’t work.

**System Description**
```PRETTY_NAME="Ubuntu 23.04"
NAME="Ubuntu"
VERSION_ID="23.04"
VERSION="23.04 (Lunar Lobster)"
VERSION_CODENAME=lunar
ID=ubuntu
ID_LIKE=debian
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
UBUNTU_CODENAME=lunar
LOGO=ubuntu-logo
```

**KasmVNC Details**
```2207706dea84a13e66b9e4909ea4a73dc6194d3c1109ebaf3ec583f62d39db2d kasmvncserver_bionic_1.1.0_arm64.deb```

**Installation Details**
I ran ```wget github.com/kasmtech/KasmVNC/releases/download/v1.1.0/kasmvncserver_bionic_1.1.0_arm64.deb``` then tried to install it with ```sudo apt-get install ./kasmvncserver_bionic_1.1.0_arm64.deb``` and then the output:
```
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
Note, selecting 'kasmvncserver' instead of './kasmvncserver_bionic_1.1.0_arm64.deb'
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 kasmvncserver : Depends: libssl1.1 (>= 1.1.0) but it is not installable
E: Unable to correct problems, you have held broken packages.
```

That’s the furthest I’ve gotten.

Then I just tried ```sudo apt --fix-broken install``` then ```apt search libssl1.1```
 ```sudo apt install libssl1.1``` but nothing.

**Additional context**
I'm running a RPi 4 with 8GB RAM and Ubuntu 23.04

**Comment by j-travis** [comment]
It looks like you are trying to use a build thats not target for your target distro version.

You mentioned using the bionic build which is 20.04

We also publish a jammy build which is 22.04, but we do not publish a lobster (23.04) build since we currently only target the LTS versions of ubuntu.

**Comment by Paranoia8972** [comment]
Damn. That makes sense. Thanks! Ubuntu 23.04 isn't that important for me so 22.04 LTS will do the job too. I'll have a look at it tomorrow.
