### ISSUE TITLE
/websockify endpoint fails when web server is served with a path prefix

### ISSUE THREAD

**Issue by Nedved-liao** [kasmtech/KasmVNC#166]
**Describe the bug**
This problem can be solved by modifying app/ui.js in novnc, but the modification does not take effect in kasmVNC

more detail:
https://github.com/novnc/noVNC/issues/1737

How to solve this problem

**Comment by mmcclaskey** [comment]
No code needs to be modified, use a reverse proxy. KasmVNC is used with Kasm Workspaces and in that configuration the KasmVNC session is has a long prefix, for example,

`wss://192.168.25.2/desktop/6603159b-49b2-45e1-8c3f-f080c19081db/vnc/websockify`

The GUID in the path a session ID that corresponds to a container. NGINX proxies the session to the correct container and alters the location when proxied to KasmVNC. When the request gets to KasmVNC it is at the correct URI.

You should be able to do something similar.
