### ISSUE TITLE
Issue Report

### ISSUE THREAD

**Issue by MikePadge** [kasmtech/KasmVNC#167]
I have a bug to report.

It's criminal more people don't know about this project. Been a long time since I've seen VNC given this much love, and I'm all for it, because Kasm is so much more than that. 

Philosophy here is awesome, thanks for the hard work put into this stuff. It's not going unnoticed. 
there's about to be a VMWare Horizon sized hole where Broadcom now is, and this type of setup solves a lot of HPC data center / cluster setup problems I've seen. 

Yall can close this, just wanted to show some love.

**Comment by mmcclaskey** [comment]
Your feedback is much appreciated! Looking forward to filling some holes created by the Broadcom deal and recent Citrix vulnerabilities :)
