### ISSUE TITLE
[Bug] -  KasmVNC Firefox SSL_ERROR_NO_CYPHER_OVERLAP

### ISSUE THREAD

**Issue by bennypr0fane** [kasmtech/KasmVNC#169]
**Describe the bug**
Upon navigating to the KasmVNC URL, SSL handshake fails

**To Reproduce**
1. start KasmVNC server
2. Under Debian Bullseye, enter the URL printed by vncserver into Firefox 
3. Firefox dsiplays an error message, containing this: "SSL_ERROR_NO_CYPHER_OVERLAP"
4. The Kasm logs on the server output the following:
```
  2023-08-07 00:11:38,433 [INFO] websocket 12: got client connection from 192.168.1.10
547432161024:error:1417A0C1:SSL routines:tls_post_process_client_hello:no shared cipher:../ssl/statem/statem_srvr.c:2283:
 2023-08-07 00:11:38,437 [DEBUG] websocket 12: using SSL socket
 2023-08-07 00:11:38,437 [DEBUG] websocket 12: Read error during handshake: Success
 2023-08-07 00:11:38,437 [DEBUG] websocket 12: No connection after handshake
 2023-08-07 00:11:38,437 [DEBUG] websocket 12: handler exit
```

**Expected behavior**
A connection to the server should be established when entering the server's URL in the browser

**Screenshots**

![Screenshot_20230807_004051](https://github.com/kasmtech/workspaces-issues/assets/5002396/85a47261-62f2-4888-bf22-81c87e0b1613)

**Workspaces Version**
KasmVNC version 1.1.0

**Workspaces Installation Method**
 Package used for installation:
https://github.com/kasmtech/KasmVNC/releases/download/v1.1.0/kasmvncserver_bullseye_1.1.0_arm64.deb
installed according to instructions in docs, using apt-get .

**Client Browser (please complete the following information):**
 - OS: Fedora 38
 - Browser: Firefox
 - Version: 116.0

**Workspace Server Information (please provide the output of the following commands):**
 - $ uname -a
Linux rasPi 6.1.21-v8+ #1642 SMP PREEMPT Mon Apr  3 17:24:16 BST 2023 aarch64 GNU/Linux
 - `$ cat /etc/os-release
PRETTY_NAME="Debian GNU/Linux 11 (bullseye)"
NAME="Debian GNU/Linux"
VERSION_ID="11"
VERSION="11 (bullseye)"
VERSION_CODENAME=bullseye
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"
 - sudo docker info: not applicable
 Package used for installation:
https://github.com/kasmtech/KasmVNC/releases/download/v1.1.0/kasmvncserver_bullseye_1.1.0_arm64.deb

**Additional context**
The server is a Raspberry Pi 4. Connection is made on the local network, no internet involved. UFW is not installed on the server. Disabling all browser extensions does not fix it.

**Comment by mmcclaskey** [comment]
KasmVNC utilizes openssl and should support cyphers configured on the system. When your browser connects to the server (KasmVNC) the client and server negotiate on what ciphers to use. In your case they were unable to find ciphers that both sides supported. This is not a configuration of KasmVNC but a configuration of openssl on your server and potentially firefox. I would start by looking at your openssl configuration on your server to see what ciphers are supported.

**Comment by mmcclaskey** [comment]
No feedback from submitter, closing.
