### ISSUE TITLE
Hiding left settings Bar completely

### ISSUE THREAD

**Issue by ne0YT** [kasmtech/KasmVNC#175]
**Is your feature request related to a problem? Please describe.**
I want to use the full screen in my remote machine to not have anyhting distracting the view there.
so I woul love to disable this sidebar completely.

**Describe the solution you'd like**
I would love to just pass a variable when starting vncserver to hide the bar

**Comment by mmcclaskey** [comment]
If KasmVNC is running inside an iframe it will hide the control panel.

**Comment by ne0YT** [comment]
@mmcclaskey but this is not an option to just set in KasmVNC? It would be more comfortable than to setup a website just for this feature.

**Comment by ne0YT** [comment]
is there something I could pass with my Caddy -reverse-proxy in front of it?
