### ISSUE TITLE
pass the username as a variable like "export username = hereshouldbethebasic-auth -username"

### ISSUE THREAD

**Issue by ne0YT** [kasmtech/KasmVNC#177]
**Is your feature request related to a problem? Please describe.**
I want to pass the username as a variable like "export username = hereshouldbethebasic-auth -username"
this way I could run a tool which wants to know my username directly

**Describe the solution you'd like**
I want that the username I used to log in being available inside my session as a variable.

**Comment by mmcclaskey** [comment]
This is possible with bash scripting, there is no need to code for it. You need to automate your host environment to configure Kasm and kasm users to meet your requirements.

**Comment by ne0YT** [comment]
"This is possible with bash scripting, there is no need to code for it. You need to automate your host environment to configure Kasm and kasm users to meet your requirements."

it would be a lot easier in my situation, if it was possible the way I asked for.

**Comment by ne0YT** [comment]
ok, yeah thx :)

**Comment by Jessica-Ruhan-Yin** [comment]
Hi, I am also experiencing a similar situation.

I am trying to run `kasmweb/ubuntu-jammy-desktop` image on a Kubernetes cluster, and I want to customize username and password for different users. Now the `kasmweb/ubuntu-jammy-desktop` image seems to have the username hardcoded as `kasm_user`. Is there a way for me to customize username as a environment variable? If I need to customize some bash scripts or Dockerfiles, could you please point me some links? Thank you so much!
