### ISSUE TITLE
starting vncserver while passing username and password directly

### ISSUE THREAD

**Issue by ne0YT** [kasmtech/KasmVNC#178]
**Is your feature request related to a problem? Please describe.**
as of right now. I need to setupt he user to connect manually while I just have one config per linux user.
I am able to start a session with passing a specific xstartup-file. But it would make my life a lot easier if I could pass a username and password while passing my xstartup-file al in one line.

it doesnt need to save this config at all, I only want to pass it for a "one-time use".

**Describe the solution you'd like**
vncserver --username mytest@test.com --password changeme -xstartup /usr/share/kasmxstartup

**Describe alternatives you've considered**
creating users manually

**Comment by mmcclaskey** [comment]
This would not be a secure implementation, as anyone on the system could run ps and get the arguments used in the command, to include your password. Given that this can already be achieved via scripting, I don't see a reason for Kasm to implement this request.
