### ISSUE TITLE
dose not work in subpath

### ISSUE THREAD

**Issue by liyimeng** [kasmtech/KasmVNC#182]
**Describe the bug**
A clear and concise description of what the issue is.

I put kasmVNC behind a proxy, which I only have single domain for use. i.e. 
instead of connect to `https://kasmvnc.mydomain.com/` I need to connect to `https://www.mydomain.com/kasmvnc/?path=/kasmvnc/websockify`

The client seems not possible to find correct path to websockify and failed with error 
`wss://www.mydomain.com/websockify` connection failed. path parameter seems ignored.

This work fine with original noVNC when I pass path correctly though. 

**System Description**
Provide the output of 
```bash
root@fd50335b776a:/# cat /etc/os-release 
NAME="Alpine Linux"
ID=alpine
VERSION_ID=3.18.3
PRETTY_NAME="Alpine Linux v3.18"
HOME_URL="https://alpinelinux.org/"
BUG_REPORT_URL="https://gitlab.alpinelinux.org/alpine/aports/-/issues"


```

**KasmVNC Details**
Provide the filename of the package you installed KasmVNC with. The filename includes important details like the OS, architecture, and commit sha.

Provide the output of this command.
```bash
root@fd50335b776a:/# Xvnc -version

Xvnc KasmVNC 1.1.0 - built Aug 22 2023 21:16:36
Copyright (C) 1999-2018 KasmVNC Team and many others (see README.me)
See http://kasmweb.com for information on KasmVNC.
Underlying X server release 12014000, The X.Org Foundation

```

**To Reproduce**
Steps to reproduce the behavior (for non-installation issues):
1. start kasmvnc instance `docker  run -it --rm -p 3000:3000 -p 3001:3001  linuxserver/chromium`
2. Configure ingress using subpath kasmvnc, pointing to docker:3000
3. try to connect with `https://www.mydomain.com/kasmvnc/?path=/kasmvnc/websockify`
4. See `wss://www.mydomain.com/websockify` connection failed. 

**Expected behavior**

kasmvnc should just connect and works

**Browser**
If this is a problem with the KasmVNC client, provide details about the browser you are accessing KasmVNC from.
 - Device: Macbook air 
 - OS: OSX
 - Browser: safari
 - Version: 16.5.2

**Additional context**

If I go to settings page, manually configure the path, it works as in noVNC

**Comment by mmcclaskey** [comment]
This is an issue with your proxy configuration, we cannot support your custom proxy. We know KasmVNC works in the configuration you desire, because that is exactly how it is implemented in Kasm Workspaces.
