### ISSUE TITLE
KasmVNC and keyboard interpretation in terminal

### ISSUE THREAD

**Issue by alphajoza** [kasmtech/KasmVNC#186]
What is the proper way to configure keyboard settings so that the terminal in desktop (xfce4) applies the keys such as tab, arrow keys the right way (as they behave in a normal terminal)?

Right now, press the tab key adds a literal tab to terminal (rather than completing the input), pressing ctrl+L adds literal ^L text (rather than clearing the terminal) and pressing arrow keys add symbols such as ^[[A^[[B^[[C^[[D

I'm using the default `/etc/kasmvnc/kasmvnc.yaml`

![Screenshot_1](https://github.com/kasmtech/KasmVNC/assets/16447592/78dd90e0-12d6-4482-99c8-807f3cd8f9fc)

**Comment by ledestin** [comment]
It's likely you're running `sh` shell in the terminal. Try running `bash`, it should solve those issues.

**Comment by alphajoza** [comment]
You are right. Using `bash` fixed the issue immediately! Thanks
