### ISSUE TITLE
What is the proper way to run Firefox?

### ISSUE THREAD

**Issue by alphajoza** [kasmtech/KasmVNC#187]
When running KasmVNC (`vncserver`) under `root` (Ubuntu 22.04 with `xfce4`), I cannot see and run Firefox (the icon doesn't even show up in the Applications menu) and if I try to run it via shell, I get:

```
No protocol specified
Error: cannot open display: :1.0
```

I suspected that maybe something is wrong with the installation of Firefox, so I installed `xrdp` and after remoting into the machine (as `root`), Firefox was present and could work without any issue.

**screenshot under KasmVNC:**
![Screenshot_kasmvnc](https://github.com/kasmtech/KasmVNC/assets/16447592/24573501-10e4-4107-b13e-64ccd7854406)

**screenshot under RDP:**
![Screenshot_rdp](https://github.com/kasmtech/KasmVNC/assets/16447592/1aaeffaa-a2de-42d2-afe8-872a53fc3b58)

**Comment by mmcclaskey** [comment]
This is a system level question and not a matter of KasmVNC. If you want an example of running Firefox on Ubuntu 22.04 with XFCE, you can check out our Jammy desktop container

https://github.com/kasmtech/workspaces-images/blob/develop/dockerfile-kasm-ubuntu-jammy-desktop
