### ISSUE TITLE
How to check whether WebRTC UDP is enabled successfully ?

### ISSUE THREAD

**Issue by DengJianShen** [kasmtech/KasmVNC#188]
KasmVNC 1.2.0

network.udp.public_ip   auto
network.udp.port           auto

Enable WebRTC UDP Transit

**Comment by mmcclaskey** [comment]
First, keep in mind that the server running KasmVNC needs to have a direct public IP address, the server cannot be behind NAT. It can be behind static 1 to 1 NAT, such as a VM in AWS that has a public IP, but it cannot be behind dynamic NAT where more than one server is associated with the same public IP.

From the KasmVNC client control panel, enable debug logging. Then open up devtools in your browser and go to the console tab in devtools. Then refresh the page. The initial connection is websocket, it then attempts an upgrade to WebRTC UDP. You should see a 'UDP Upgrade recieved from server...' message followed by a success or failure. Look for any red messages in the console if you don't see the UDP upgrade recieved from server message.

You should also see logs server side. Tail the logs under $HOME/.vnc/<session_name>.log
