### ISSUE TITLE
Strange behavior with clipboard paste requiring click before pasting

### ISSUE THREAD

**Issue by valankar** [kasmtech/KasmVNC#192]
**Describe the bug**
I noticed that clipboard paste doesn't work with the latest data in the clipboard unless there is first a click in the KasmVNC window. It seems to only paste the latest data when I first click in the KasmVNC window. Sometimes I alt-tab from another app or Edge tab after copying text, expecting I can paste without clicking, but it doesn't work.

**System Description**
Provide the output of 
```bash
root@663a2c6d02c6:/# cat /etc/os-release
NAME="Alpine Linux"
ID=alpine
VERSION_ID=3.18.4
PRETTY_NAME="Alpine Linux v3.18"
HOME_URL="https://alpinelinux.org/"
BUG_REPORT_URL="https://gitlab.alpinelinux.org/alpine/aports/-/issues"
root@663a2c6d02c6:/# uname -a
Linux 663a2c6d02c6 6.1.0-12-amd64 #1 SMP PREEMPT_DYNAMIC Debian 6.1.52-1 (2023-09-07) x86_64 GNU/Linux
```

**KasmVNC Details**
Provide the filename of the package you installed KasmVNC with. The filename includes important details like the OS, architecture, and commit sha.
https://hub.docker.com/layers/linuxserver/webtop/alpine-i3/images/sha256-ae4ae282545ccbbb50123030dbe956adff47b38ff71a4a5cf424db9c4a9611ba?context=explore

Provide the output of this command.
```bash
Xvnc -version
Xvnc KasmVNC 1.2.0 - built Sep 30 2023 18:47:05
Copyright (C) 1999-2018 KasmVNC Team and many others (see README.me)
See http://kasmweb.com for information on KasmVNC.
Underlying X server release 12014000, The X.Org Foundation
```

**To Reproduce**
Steps to reproduce the behavior (for non-installation issues):
1. Create 2 tabs in web browser with one tab connected to KasmVNC and a terminal open (st, xterm, alacritty, etc).
2. Copy some text in the non-KasmVNC tab.
3. Switch to KasmVNC tab.
4. Press ctrl-shift-v to paste (without clicking in the KasmVNC window). Either nothing or an old paste buffer is pasted.
5. Click in the KasmVNC window.
6. Press ctrl-shift-v to paste. The latest copied data is pasted.

**Expected behavior**
The latest clipboard data should be pasted without requiring a click in the KasmVNC window.

**Browser**
If this is a problem with the KasmVNC client, provide details about the browser you are accessing KasmVNC from.
 - Device: PC
 - OS: Windows 10
 - Browser: Edge 
 - Version: 117.0.2045.47 (Official build) (64-bit)

**Comment by mmcclaskey** [comment]
This is a browser limitation (security feature of Chrome) that does not allow us to read your clipboard unless the read comes from a user driven event. Thus, we can only read your local clipboard on an event that chrome classifies as user driven, such as a click on a dom element (the canvas).
