### ISSUE TITLE
Pre-compiled binaries for CentOS 7

### ISSUE THREAD

**Issue by kasmtech** [kasmtech/KasmVNC#2]

**Comment by ledestin** [comment]
@clbr I'm getting an `rpmlint` error:
```
kasmvncserver.x86_64: E: missing-call-to-setgroups /usr/bin/Xkasmvnc
```

`Xkasmvnc` == `Xvnc`. Would it be a good idea to fix it?

**Comment by clbr** [comment]
The upstream X server does not do so either. It's related to dropping privileges, which neither we nor the upstream X do.

**Comment by clbr** [comment]
Adding: why would dropping privs be required? I run kasmvnc as an user, it does not need root rights.

**Comment by ledestin** [comment]
Because of `setuid`, I suppose.

```
nm /tmp/tmp.o8ydt1sKnl/usr/local/bin/Xvnc  | grep setuid
                 U setuid@@GLIBC_2.2.5
```

I've checked, and TigerVNC has the same error, so I guess we could just ignore it.
