### ISSUE TITLE
Restart one users session / halt one users session

### ISSUE THREAD

**Issue by ne0YT** [kasmtech/KasmVNC#202]
I would like to restart just one users session. kasmstartup changed and I want to test it on users which are there already.
also I would like to temporarily halt it's session.

**Comment by mmcclaskey** [comment]
You are going to have to be a lot more specific, perhaps a user story that walks through the different scenarios, what the current behavior is and what the desired behavior is for each user story.

**Comment by ne0YT** [comment]
the current behaviour is that I have multiple users which are on the same KASM Setup. they are automatically starting if the service is running.

I would like to pause this for one user at a time so I can kill his current session (I would just kill everything running under that user) and then start his session later on again.
this way I can modify his logon-script I'm using / keep a user from connecting temporarily.

**Comment by mmcclaskey** [comment]
This sounds like it would be handled through system engineering, I'm sorry but I won't be able to help with that. I can, however, point you to how we manage KasmVNC and the desktop environment in our containers. See the vnc_startup.sh script, you can see that we do not use the .vnc/xstartup script at all, it is left empty. We start xfce4 ourselves in the script. We also monitor KasmVNC and Xfce and if either crashes we restart them. You should be able to achieve your desired outcome through similar techniques.

https://github.com/kasmtech/workspaces-core-images/blob/develop/src/common/startup_scripts/vnc_startup.sh
