### ISSUE TITLE
404 /websockify issue

### ISSUE THREAD

**Issue by uhidontkno** [kasmtech/KasmVNC#205]
**Describe the bug**
I'm trying to use noVNC with a Kasm container with kasmVNC running, and I'm trying to access the direct /websockify WebSockets endpoint, but instead of 101, or anything I get hit with 404.
```
 2023-12-11 04:34:46,532 [INFO] websocket 4: got client connection from 127.0.0.1
 2023-12-11 04:34:46,532 [INFO] websocket 4: /websockify request failed websocket checks, missing Sec-WebSocket-Origin header
 2023-12-11 04:34:46,532 [INFO] websocket 4: 127.0.0.1 172.17.0.1 - "GET /websockify HTTP/1.1" 404 180
```

**System Description**
```bash
PRETTY_NAME="Debian GNU/Linux 12 (bookworm)"
NAME="Debian GNU/Linux"
VERSION_ID="12"
VERSION="12 (bookworm)"
VERSION_CODENAME=bookworm
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"
Linux debian 6.1.0-13-amd64 #1 SMP PREEMPT_DYNAMIC Debian 6.1.55-1 (2023-09-29) x86_64 GNU/Linux
```

**KasmVNC Details**
I'm using the KasmVNC installed on Kasm's official Docker containers, so I am assuming the latest version.

Xvnc version TightVNC-1.3.10

**To Reproduce**
Steps to reproduce the behavior (for non-installation issues):
1. Access /websockify path using WebSockets without using the KasmVNC client (eg. noVNC)

**Expected behavior**
A WebSockets connection to be made using an external client like noVNC.

**Additional context**
I'm trying to proxy HTTP, HTTPS, and WebSocket requests using a Node server and I wanted to try and access my container via VNC using the proxy, as I need to access many containers without exposing so many ports, but when I try and access my container's /websockify path, I get hit with a 404. I am unable to use my container's KasmVNC because I am accessing it from a path like /https/3000 and the client is trying to make a websockets connection to /websockify instead of /https/3000/websockify.

**Comment by mmcclaskey** [comment]
I'm sorry, but we are unable to assist with custom integration like this. I can point you in the right direction though. Kasm Workspaces uses NGINX to change the path of /websockify and so it should be possible. Not all proxies support websockify or if they do, they need to be explicitly configured to do so. I do not use node, and have no idea what server you are using, so check their docs to ensure it supports websockify and if there is any configuration you need to do it make it work. 

Getting a proxy to change the path of one location to another location in the URL path is supported by noVNC, check the documentation of your proxy to ensure you have this configured correctly. There is nothing special that needs to be done by KasmVNC/noVNC to support that, it is all on the proxy being configured appropriately.

**Comment by uhidontkno** [comment]
I'm not using Kasm Workspaces, I'm manually launching a container from the command line. I'm also using my custom proxy.
