### ISSUE TITLE
404 /websockify issue using Nginx

### ISSUE THREAD

**Issue by uhidontkno** [kasmtech/KasmVNC#215]
**Describe the bug**
I'm trying to proxy my Docker containers behind Nginx so I can open less ports, and I'm trying to proxy KasmVNC's websockify server so I can connect to it using NoVNC. The server returns a 404 instead of a 101.

**System Description**
```
PRETTY_NAME="Debian GNU/Linux 12 (bookworm)"
NAME="Debian GNU/Linux"
VERSION_ID="12"
VERSION="12 (bookworm)"
VERSION_CODENAME=bookworm
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"
Linux LATITUDE-V2 6.1.0-17-amd64 #1 SMP PREEMPT_DYNAMIC Debian 6.1.69-1 (2023-12-30) x86_64 GNU/Linux
```

**KasmVNC Details**

This is being ran on the official Kasm Workspaces images, VNC was not installed on the host.

----
```bash
$ Xvnc -version
bash: Xvnc: command not found
```
VNC was not installed.

**To Reproduce**
1. Use the below nginx configuration
2. Run a Kasm Workspaces image with KasmVNC over any port (let's say 6901)
3. Try to connect with a different client, eg NoVNC with the url `localhost:8000/6901/websockify`
4. If replicated correctly, in DevTools you'll see a 404.

**Expected behavior**
The WebSockets connection to be successfully proxied.

**Browser**
Not applicable

**Additional context**
* KasmVNC was used over HTTP.
* Nginx configuration:
```
user www-data;
worker_processes auto;
pid /run/nginx.pid;
include /etc/nginx/modules-enabled/*.conf;

events {
        worker_connections 768;
}

http {
        sendfile on;
        tcp_nopush on;
        types_hash_max_size 2048;
        include /etc/nginx/mime.types;
        default_type application/octet-stream;
        ssl_protocols TLSv1 TLSv1.1 TLSv1.2 TLSv1.3; # Dropping SSLv3, ref: POODLE
        ssl_prefer_server_ciphers on;

        access_log /var/log/nginx/access.log;
        error_log /var/log/nginx/error.log;
        gzip on;
        include /etc/nginx/conf.d/*.conf;
        include /etc/nginx/sites-enabled/*;
        server {
            listen 8000;

            location ~ ^/(\d+)/(.*)$ {
               proxy_pass http://127.0.0.1:$1/$2;
               proxy_http_version 1.1;
               proxy_set_header Upgrade $http_upgrade;
               proxy_set_header Connection "upgrade";
               proxy_set_header Host $host;
               proxy_set_header X-Real-IP $remote_addr;
               proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
               proxy_set_header X-Forwarded-Proto $scheme;

               # WebSocket support
               proxy_set_header Upgrade $http_upgrade;
               proxy_set_header Connection "upgrade";
        }
      }

}
```

**Comment by mmcclaskey** [comment]
It is definitely possible, we use NGINX to route traffic to the correct container within our platform. As much as I personally love NGINX riddles, we can't provide support for NGINX problems. But I may be able to provide a few points off the top of my head.

I've never seen someone use capture groups from a location regex and try to use it in a proxy_pass directive, I don't think that is possible, but I only spent about 60 seconds googling that. Read this post on StackExchange, it seems you should be getting capture group values from a rewrite, not the location regex.

https://serverfault.com/questions/1080986/using-a-part-of-the-uri-as-a-port-number-for-nginx-proxy-pass-directive

Also, you are proxy passing to http while KasmVNC runs https by default.

**Comment by uhidontkno** [comment]
Not a nginx issue @mmcclaskey 
```
2024-02-15 02:28:26,719 [INFO] websocket 7: got client connection from 127.0.0.1
2024-02-15 02:28:26,719 [INFO] websocket 7: /websockify request failed websocket checks, not a GET request, or missing Upgrade header - this was a proper WS request
2024-02-15 02:28:26,719 [INFO] websocket 7: 127.0.0.1 192.168.0.204 - "GET /websockify/ HTTP/1.1" 404 180
2024-02-15 02:32:16,587 [PRIO] Connections: closed:  @192.168.0.204_1707963714.224839::websocket (Clean disconnection)
2024-02-15 02:32:17,802 [INFO] websocket 8: got client connection from 127.0.0.1
2024-02-15 02:32:17,810 [PRIO] Connections: accepted: - official client @192.168.0.204_1707964337.802830::websocket
```

**Comment by Frontesque** [comment]
I recently attempted to use noVNC with a standalone KasmVNC instance aswell. I see the same issue. I just resorted to just using a static copy of the KasmVNC client ([KasmVNC_Client.zip](https://github.com/kasmtech/KasmVNC/files/14380242/KasmVNC_Client.zip)) I can provide instructions on how to obtain the attached files if it would help.

**Comment by uhidontkno** [comment]
> I recently attempted to use noVNC with a standalone KasmVNC instance aswell. I see the same issue. I just resorted to just using a static copy of the KasmVNC client ([KasmVNC_Client.zip](https://github.com/kasmtech/KasmVNC/files/14380242/KasmVNC_Client.zip)) I can provide instructions on how to obtain the attached files if it would help.

I've decided to go [do it myself](https://github.com/Deblok-Workshop/DeblokDocker) because even IF I use stock kasm or LinuxServer.io images I get the same thing. Making the containers yourself is a headache but it pays off when everything just works.

**Comment by Frontesque** [comment]
> I've decided to go [do it myself](https://github.com/Deblok-Workshop/DeblokDocker) because even IF I use stock kasm or LinuxServer.io images I get the same thing and I could not figure out how to deploy just the kasmvnc client. Making the containers yourself is a headache but it pays off when everything just works.

Alright, I'll check it out, though I did get my kasmvnc instance working fine. I'm really not a fan of Kasm's whole mentality of "just don't do it that way" for a lot of things. If you look at proxying their containers, they basically tell you not to, though I found a really simple way to do it after modifying their client slightly, but they'll go ape shit on anyone suggesting that you do that. 

If you do need help though, I'm sticking with my custom kasm client and am willing to provide assistance to anyone who is looking to do what this issue entails.

**Comment by uhidontkno** [comment]
> > I've decided to go [do it myself](https://github.com/Deblok-Workshop/DeblokDocker) because even IF I use stock kasm or LinuxServer.io images I get the same thing and I could not figure out how to deploy just the kasmvnc client. Making the containers yourself is a headache but it pays off when everything just works.
> 
> Alright, I'll check it out, though I did get my kasmvnc instance working fine. I'm really not a fan of Kasm's whole mentality of "just don't do it that way" for a lot of things. If you look at proxying their containers, they basically tell you not to, though I found a really simple way to do it after modifying their client slightly, but they'll go ape shit on anyone suggesting that you do that. 
> 
> If you do need help though, I'm sticking with my custom kasm client and am willing to provide assistance to anyone who is looking to do what this issue entails.
> 

I'm really not a big fan of Kasm's bullshit and overpriced licensing... The free limits are way too low and you can only handle a small handful of people at the same time regardless of your computing resources. I need to overcome this without paying over **$1,200** for increased concurrent sessions, so I had to [remake Kasm from scratch](https://GitHub.com/Deblok-Workshop/NewDeblok) which is the entire reason why I need to run these containers outside of Kasm itself.
