### ISSUE TITLE
Support "inetd mode" with websocket

### ISSUE THREAD

**Issue by acarapetis** [kasmtech/KasmVNC#224]
We're currently using lightdm+tigervnc+websockify+novnc to provide a multi-user remote desktop solution to our users. If possible, we'd like to switch to KasmVNC for its superior compression features; but as far as I can tell there's currently no way to use lightdm's VNC support with KasmVNC's websocket connections.

Based on a quick look at its source code, lightdm's VNC server doesn't depend on anything about the rfb protocol - it simply listens for TCP connections, and connects each client's socket to the stdin/stdout of a new Xvnc server in `-inetd` mode. In theory this means it should work for websockets, too - if kasm's Xvnc had an `-inetdWebsocket` flag that made it speak Websocket on stdin/stdout, I believe we could plug it directly into lightdm and be on our way.

Maybe I'm wrong about that - let me know if so! Also open to suggestions for other approaches to providing a multi-user server without having a session constantly alive for every user.

**Comment by acarapetis** [comment]
My hunch that this would work seems to be correct - using this python wrapper script instead of Xvnc in my lightdm config works! Still, would be nice to have native support :)

```python
#!/usr/bin/env python3
"""Runs Kasm's Xvnc in websocket mode, but exposing access to the socket via
stdio as expected by inetd and lightdm."""

import os # anyone know an alternative that starts with the letters? this o is ruining my vibe
import signal
import socket
import subprocess
import sys

# lightdm provides -inetd, which we don't want, so strip that out:
args = [x for x in sys.argv[1:] if x != "-inetd"]

# Get a free port
s = socket.socket()
s.bind(('', 0))
port = s.getsockname()[1]
s.close()

print(f"Starting Xvnc on websocket port {port}", file=sys.stderr, flush=True)
cmd = ["Xvnc", "-websocketPort", str(port), "-httpd", "/usr/share/kasmvnc/www", "-interface", "0.0.0.0", "-KasmPasswordFile", "/root/.kasmpasswd", *args]
print(cmd, file=sys.stderr, flush=True)

# Start kasmVNC on that port (listening for websockets)
proc = subprocess.Popen(cmd)

# X servers send SIGUSR1 to their parent process when they're ready to go.
# lightdm relies on this, so we need to relay it up.
# This must be done AFTER starting the subprocess, since X only sends the
# signal if the handler for SIGUSR1 is currently SIG_IGN.
def handle_usr1(signum, frame):
    print(f"{os.getpid()} sending USR1 to {os.getppid()}", file=sys.stderr, flush=True)
    os.kill(os.getppid(), signal.SIGUSR1)

signal.signal(signal.SIGUSR1, handle_usr1)

# Connect stdin/stdout to the port
# Retry for 3 seconds to give Xvnc a chance to start
subprocess.run(["socat", f"TCP4:localhost:{port},retry=3,interval=1", "STDIO"])

# kill the X session when the connection ends
proc.kill()
```

**Comment by mmcclaskey** [comment]
I gather that you want to support multiple users on a single server.

We may eventually look to solve this, but I'm not sure it would be by the use of inetd. We solve for this in Kasm Workspaces by using containers and dynamic NGINX configurations to direct users to the right port on the right container. I would suggest a similar implementation, by writting a middleware API that puppets KasmVNC and NGIXN on the host.

That is of course outside the scope of KasmVNC. Perhaps at some point we will consider a better systemd service that will control KasmVNC and help to better facilitate concurrency within a system and manage user sessions.

**Comment by acarapetis** [comment]
@mmcclaskey Developing our own middleware would be a large effort that we can't really justify when lightdm suits our needs perfectly well. All KasmVNC needs to do to support lightdm is have an option to accept a websocket connection via stdio - this seems within scope to me? If we implemented such a patch would a PR be accepted?

**Comment by acarapetis** [comment]
@bsdice Nope, sorry.
