### ISSUE TITLE
Mousewheel ends up beeing translated as text on secondary monitor

### ISSUE THREAD

**Issue by Husky110** [kasmtech/KasmVNC#225]
**Describe the bug**
I hope that this is indeed a bug in KasmVNC and not the Workspaces-project itself...  
What happens is this that when I add a second monitor to my session and got said secondary monitor in fullscreen (not sure if fullscreen is the issue here) that sometimes using the mouse wheel to scroll up or down gets translated into text (see attached screenshoot). Which is very disturbing in Dev-Environments. So far I've been only able to recreate this behavior in the secondary monitor. The primary one works fine.  
![image](https://github.com/kasmtech/KasmVNC/assets/13180625/2c448866-f08c-4049-a3d3-0a2fbbbea8cd)

**KasmVNC Details**
The container-image is a modified version of `kasmweb/ubuntu-jammy-dind-rootless:1.15.0` (build and pushed to my private repo about an hour ago). Modifcations only install some programms: PHPStorm, PHP8.1 and composer. Nothing I would suspect to interfer here. I connect via Google Chrome from Ubuntu 22.04 on said container. 

**To Reproduce**
Steps to reproduce the behavior (for non-installation issues):
1. Setup a container using the `kasmweb/ubuntu-jammy-dind-rootless:1.15.0` -image.
2. Add a secondary monitor and put it in full screen.
3. Open any Texteditor (I was able to reproduce the behaviour in PHPStorm and DBeaver, so I think it's a general issue) and put it on said secondary monitor maximized.
4. Make sure the cursor in the TextEditor is ready to receive input!
5. Use the mousewheel to "scroll" up and down - do it fast and slow, like "propperly testing" (don't know of better description here) and you might see weird signs like in the screenshoot above.

**Expected behavior**
Propper mouse wheel-function...

**Browser**
If this is a problem with the KasmVNC client, provide details about the browser you are accessing KasmVNC from.
-> I am not sure where exactly this comes from...  
Edit: Might be important for testing: I'm using KasmWorkspace within my WLAN. So I am not sure if that bug occures when testing on a local machine!

**Comment by mmcclaskey** [comment]
Fixed with [latest release](https://github.com/kasmtech/KasmVNC/releases/tag/v1.3.1)

**Comment by Husky110** [comment]
@mmcclaskey - Is this new release already baked into the 1.15.0-images of KasmWorkspaces?
