### ISSUE TITLE
Multiple users issues (users branch)

### ISSUE THREAD

**Issue by ledestin** [kasmtech/KasmVNC#23]
I've merged `users` branch into `packages_and_multiuser_passwd` branch and tried it out. I fixed merge conflicts and it has the latest deb/rpm packages.

1. -w user works fine.
2. ro user has no cursor. I understand it wouldn't click anything, but it is annoying.
3. -o user (owner) has cursor at a fixed position and same as read-only otherwise.

@clbr could you please make it possible to set/verify password via stdin that isn't a tty?
```
echo foobar | kasmvncpasswd -w -u $VNC_USER $HOME/.kasmpasswd
getpass error: Inappropriate ioctl for device
```

**Comment by clbr** [comment]
> 2. ro user has no cursor. I understand it wouldn't click anything, but it is annoying.

Client-side decision I believe. Some viewers show it, novnc apparently
not.

> 3. -o user (owner) has cursor at a fixed position and same as read-only otherwise.

The owner permission is separate from write. Owner only means he can
dynamically change who has write perm (not implemented yet IIRC). The
owner may or may not have write perms.

> @clbr could you please make it possible to set/verify password via stdin that isn't a tty?

Pushed. It was already possible, but it printed the prompts which
didn't look nice.
