### ISSUE TITLE
full disable auth

### ISSUE THREAD

**Issue by procolost** [kasmtech/KasmVNC#232]
i use nginx with pam auth.
how to disable auth in kasm?

**Comment by mmcclaskey** [comment]
KasmVNC uses HTTP Basic authorization. You can hard code the credentials in your nginx configuration.

https://stackoverflow.com/questions/43821612/authorization-header-in-nginx-for-proxying-to-basic-auth-backend-doest-work

**Comment by Niek** [comment]
You can use `-SecurityTypes None -disableBasicAuth`
