### ISSUE TITLE
Call developer API while disableBasicAuth

### ISSUE THREAD

**Issue by namlh-eureka** [kasmtech/KasmVNC#234]
**Describe the bug**
Cannot call Developer API when set `disableBasicAuth`

**System Description**
```
PRETTY_NAME="Ubuntu 22.04.3 LTS"
NAME="Ubuntu"
VERSION_ID="22.04"
VERSION="22.04.3 LTS (Jammy Jellyfish)"
VERSION_CODENAME=jammy
ID=ubuntu
ID_LIKE=debian
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
UBUNTU_CODENAME=jammy
Linux vnc-trial-1 6.2.0-1018-aws #18~22.04.1-Ubuntu SMP Wed Jan 10 22:54:16 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux
```

**KasmVNC Details**
```
Xvnc KasmVNC 1.2.0.2af2e661e9906b5778644f6e2fbe1f51cebb337a - built Sep 13 2023 23:49:36
Copyright (C) 1999-2018 KasmVNC Team and many others (see README.me)
See http://kasmweb.com for information on KasmVNC.
Underlying X server release 12008000, The X.Org Foundation
```

**To Reproduce**
1. I disable basic auth by using `-disableBasicAuth`
2. Call `http://{ip}:{port}/api/get_bottleneck_stats` got `401 Unauthorized`
3. Try call `http://{ip}:{port}/api/get_bottleneck_stats` with basic auth username:password of kasmvnc but also got `401 Unauthorized`

**Expected behavior**
- Can call developer API without any auth

**Browser**
 - Browser chrome

**Comment by burnerlee** [comment]
@ledestin @CendioOssman is there any way to mitigate this? facing the same issue

**Comment by mmcclaskey** [comment]
@clbr can you confirm if using the API is explicitly not allowed if auth is disabled?

**Comment by clbr** [comment]
This is correct. The API is only allowed for Owners, and if auth is disabled, we can't determine if the caller is an owner.
