### ISSUE TITLE
How to disable brute force protection

### ISSUE THREAD

**Issue by tetebueno** [kasmtech/KasmVNC#238]
**Describe the bug**
There doesn't seem to be a straightforward way to disable brute force protection, or at least is not that easy to find in the documentation.

**System Description**

<details>
<summary>

`cat /etc/os-release` output

</summary>

```
PRETTY_NAME="elementary OS 7.1 Horus"
NAME="elementary OS"
CPE_NAME="cpe:/o:elementary:elementary_os:7.1"
VERSION_ID="7.1"
VERSION="7.1 Horus"
VERSION_CODENAME=horus
ID=elementary
ID_LIKE="ubuntu debian"
HOME_URL="https://elementary.io/"
DOCUMENTATION_URL="https://elementary.io/docs/learning-the-basics"
SUPPORT_URL="https://elementary.io/support"
BUG_REPORT_URL="https://docs.elementary.io/contributor-guide/feedback/reporting-issues"
PRIVACY_POLICY_URL="https://elementary.io/privacy-policy"
UBUNTU_CODENAME=jammy
UBUNTU_PRETTY_NAME="Ubuntu 22.04.3 LTS"
UBUNTU_NAME="Ubuntu"
UBUNTU_VERSION_ID="22.04"
UBUNTU_VERSION="22.04.3 LTS (Jammy Jellyfish)"
UBUNTU_VERSION_CODENAME=jammy
```

</details>

<details>
<summary>

`uname -a` output

</summary>

```
Linux host 6.2.0-36-generic #37~22.04.1-Ubuntu SMP PREEMPT_DYNAMIC Mon Oct  9 15:34:04 UTC 2 x86_64 x86_64 x86_64 GNU/Linux
```

</details>

**KasmVNC Details**
Provide the filename of the package you installed KasmVNC with. The filename includes important details like the OS, architecture, and commit sha.

Provide the output of this command.
```bash
Xvnc -version

Xvnc KasmVNC 1.3.1.230e50f7b89663316c70de7b0e3db6f6b9340489 - built Mar 15 2024 09:25:50
Copyright (C) 1999-2018 KasmVNC Team and many others (see README.me)
See http://kasmweb.com for information on KasmVNC.
Underlying X server release 12008000, The X.Org Foundation
```

**To Reproduce**
Steps to reproduce the behavior (for non-installation issues):
1. Try to disable brute force protection.

**Expected behavior**
A specific configuration parameter to do so.

**Additional context**
A workaround I've seen is to set `security.brute_force_protection.blacklist_threshold` option to a high value in `kasmvnc.yaml`, but seems kind of hacky.

**Comment by mmcclaskey** [comment]
Setting blacklist to 0 in v1.3.3 and later will disable brute force protection.
