### ISSUE TITLE
Feature: Add Ubuntu Noble

### ISSUE THREAD

**Issue by OhMyMndy** [kasmtech/KasmVNC#239]
Implementation of Ubuntu Noble

**Comment by mmcclaskey** [comment]
Here are the developer preview builds. They will be included in our next release..

https://kasmweb-build-artifacts.s3.amazonaws.com/kasmvnc/511e2ae542e95f5447a0a145bb54ced968e6cfec/kasmvncserver_noble_1.3.2_master_511e2a_amd64.deb

https://kasmweb-build-artifacts.s3.amazonaws.com/kasmvnc/511e2ae542e95f5447a0a145bb54ced968e6cfec/kasmvncserver_noble_1.3.2_master_511e2a_arm64.deb

**Comment by OhMyMndy** [comment]
#240

**Comment by cryptoluks** [comment]
Hello,

Thank you for maintaining this great software as open source.

I was wondering if there are any plans to push the latest Ubuntu Noble builds to this repository soon. Are there alternative public release channels for newer versions, perhaps on your GitLab instance or elsewhere? :smile:

**Comment by mmcclaskey** [comment]
We will be publishing the 1.3.2 release in a few days.
