### ISSUE TITLE
Test and merge branch Kasm-1298

### ISSUE THREAD

**Issue by kasmtech** [kasmtech/KasmVNC#25]
@ledestin , please also test and merge the following branch into master. It should only be changes to some UI files. That being said, you should only need to test one build for a single OS. The changes affect clipboard, so you should probably test copying and pasting to and from the remote system.  Thank you

https://github.com/kasmtech/KasmVNC/tree/KASM-1298_manually_merge_offline_changes

**Comment by ledestin** [comment]
@kasmtech I'm able to copy from VNC with Cmd-C, but not able to paste (MacOS, Firefox). It is the same with or without the branch `KASM-1298_manually_merge_offline_changes`.

**Comment by ledestin** [comment]
@kasmtech I was using keyboard shortcuts in Firefox. What is "clipboard from the control panel"?

I'll try Chrome on Linux tomorrow.

**Comment by mmcclaskey** [comment]
Open the KasmVNC control panel on the center left, and in there is a
clipboard text box that you have to use to move text between the local and
remote clipboards. Chrome based browsers have implemented a clipboard API
that provides javascript access to the Cliboard, therefore, we do seamless
clipboard for Chromium based browsers. Firefox, to my knowledge, has not
yet implemented this API, therefore, you have to use the control panel to
move text to and from the remote clipboard.

**Comment by ledestin** [comment]
Simply putting text into the control panel clipboard doesn't propagate it to the host, but using Cmd-C to copy text does. Pasting text works either with the control panel clipboard or directly into programs.

Safari has Basic Auth issues, so I can't get KasmVNC working at all.
