### ISSUE TITLE
File Uploads and Downloads

### ISSUE THREAD

**Issue by Pastitas** [kasmtech/KasmVNC#250]
**Is your feature request related to a problem? Please describe.**
Right now there's no action associated with dragging and dropping files on kasmvnc webpage, instead the default action by the browser is done. Also in the settings menu there's an option for file upload that, when that specific window is open, allows for file uploads via drag and drop.

**Describe the solution you'd like**
Add an togglable option to make the app upload automatically any files that are dragged and dropped there in the main page (maybe using some default upload folder setting) . 

**Describe alternatives you've considered**
If this could somehow be integrated with the vnc host to drag the same file to the used application inside would be amazing but that seems way more complex, maybe that could be a future improvement

**Additional context**
This makes sense for applications in which you'd normally want to drag and drop a file into.

**Comment by mmcclaskey** [comment]
KasmVNC itself has no file upload/download feature at all. Kasm Workspaces does, but those features are not facilitated by KasmVNC. I do believe that Kasm Workspaces already supports drag and drop for file uploads. So before drag and drop could be supported, KAsmVNC would first have to support file uploads and downloads. I will change the name of the request to reflect that.

**Comment by Pastitas** [comment]
Oh, I'm using the https://github.com/linuxserver/docker-orcaslicer image and I assumed the upload option is a feature of kasmvnc, i've opened an issue there so if you want this could be closed

**Comment by Pastitas** [comment]
moved to proper repo, excuse the noise https://github.com/kasmtech/noVNC/issues/109
