### ISSUE TITLE
unable to connect to session through reverse proxy

### ISSUE THREAD

**Issue by ardapi8443** [kasmtech/KasmVNC#251]
hi !

**Describe the bug**
using KasmVNC 1.3.1, can connect with private IP but not behind nginx PM

**System Description**
ubuntu server 20.04 (+Xfce), LXC on proxmox 8

**To Reproduce**
when i try to connect to the vnc session with the private ip:8444, everything work fine.
i'v add an entry to nginx PM and the tried to connect with the domain name (i've add websockets support)

when trying to acess it through Nginx, the auth popup is displayed but when connecting it displays me the popup again and i have a 401 Unauthorized response in the network tab

i tried to reach it by http by updating the kasmvnc.yaml to :
 network:
   ssl:
     require_ssl: false

here is the log when trying to connect via the domain name :

2024-06-03 18:02:46,530 [INFO] websocket 125: got client connection from 192.168.1.66
2024-06-03 18:02:46,531 [DEBUG] websocket 125: using plain (not SSL) socket
2024-06-03 18:02:46,531 [DEBUG] websocket 125: X-Forwarded-For ip '192.168.1.1'
2024-06-03 18:02:46,531 [INFO] websocket 125: Authentication attempt failed, BasicAuth required, but client didn't send any
2024-06-03 18:02:46,531 [INFO] websocket 125: 192.168.1.66 192.168.1.1 - "GET / HTTP/1.1" 401 158
2024-06-03 18:02:46,531 [DEBUG] websocket 125: No connection after handshake
2024-06-03 18:02:46,531 [DEBUG] websocket 125: handler exit

i've searched the issues but can't find something similar (or missed it) :(

**Comment by mattmcclaskey** [comment]
Is nginx serving http or https? I don't believe browsers will pass the authorization header if it is http.

**Comment by ardapi8443** [comment]
when trying to reach with the domain, the url is with https but chrome said it is not secure (already tried with firefox, no chance there)
it is the same as another LXC i have with a lampp stack also with basicauth with a .htpasswd

i have the same issues with nginx reaching the kasmvnc LXC either with http or https

**Comment by mattmcclaskey** [comment]
All I can tell you is that KasmVNC is not receiving the authorization header. I'm sorry I can't be of more assistance. Either nginx is not passing it or Chrome is not passing it. Check devtools of Chrome and verify that it is sending it. We use nginx and do not have issues, but I don't have insight into what you are doing.

**Comment by jghaanstra** [comment]
Has anyone found a solution to this. I'm experiencing the same issue. All works fine until using a reverse proxy. I check the devtools of Chrome but the only related header I'm seeing is `Basic realm="Websockify"`. Would be nice to get this sorted.
