### ISSUE TITLE
Possibility to build on armhf for raspberry pi os (32 bit)

### ISSUE THREAD

**Issue by Igultgithub** [kasmtech/KasmVNC#255]
Building for armhf architecture is not possible with current version. But there are a lot of single board computers with armv7 cpus, older raspberries or even RPI4 running 32bit build of raspberry pi os.

And it is possible with 2 minor adjustments to build on armhf:

at the build.sh script:
```c
 --- kasm_src/KasmVNC-1.3.1/builder/build.sh    2024-03-15 10:19:45.000000000 +0100
+++ builder/build.sh    2024-06-25 07:55:12.460097137 +0200
@@ -139,6 +139,8 @@
   ln -s /usr/lib/x86_64-linux-gnu/dri dri
 elif [ -d /usr/lib/aarch64-linux-gnu/dri ]; then
   ln -s /usr/lib/aarch64-linux-gnu/dri dri
+elif [ -d /usr/lib/arm-linux-gnueabihf/dri ]; then 
+  ln -s /usr/lib/arm-linux-gnueabihf/dri dri
 elif [ -d /usr/lib/xorg/modules/dri ]; then
   ln -s /usr/lib/xorg/modules/dri dri
 else
```

That resolves the error regarding missing swrast_dri.so at linking stage.

Afterwards there are binaries, but Xvnc segfaults. This can be resolved in websocket.c:

```c
--- kasm_src/KasmVNC-1.3.1/common/network/websocket.c  2024-06-26 07:11:04.036157537 +0200
+++ common/network/websocket.c 2024-06-24 08:48:54.169962569 +0200
@@ -934,7 +940,7 @@
     }

     fseek(f, 0, SEEK_END);
-    const unsigned long filesize = ftell(f);
+    const uint64_t filesize = ftell(f);
     rewind(f);

     sprintf(buf, "HTTP/1.1 200 OK\r\n"
``` 

Since ftell retuns long instead of uint64_t and sprintf expects long instead of uint64_t this leads to segfaults on all platforms where uint64_t and unsigned long do not match.

Afterwards Xvnc runs without problems on armhf. Built for debian bookworm, tested on RPi3/raspberry pi os and Banana Pi M3/armbian.

**Comment by clbr** [comment]
That second change has been in tree since 2022, is your diff perhaps inverted? https://github.com/kasmtech/KasmVNC/blob/master/common/network/websocket.c#LC943

Your change would revert the support for over-4gb file serving, I think changing the printf line to use priu64 from inttypes.h would be preferable.

**Comment by Igultgithub** [comment]
Yes this was the wrong direction. Unsigned long is the return value of ftell and you can format it with %ul. If you assign it to uint64_t it is still a 32 bit value on 32 bit architectures and the maximum reported file size is 2GB.

```c++
@@ -939,15 +933,15 @@
         goto nope;
     }

-    fseek(f, 0, SEEK_END);
-    const uint64_t filesize = ftell(f);
+    fseeko64(f, 0, SEEK_END);
+    const uint64_t filesize = ftello64(f);
     rewind(f);

     sprintf(buf, "HTTP/1.1 200 OK\r\n"
                  "Server: KasmVNC/4.0\r\n"
                  "Connection: close\r\n"
                  "Content-type: %s\r\n"
-                 "Content-length: %lu\r\n"
+                 "Content-length: %" PRIu64 "\r\n"
                  "%s"
                  "\r\n",
                  name2mime(path), filesize, extra_headers ? extra_headers : "");
``` 

This replaces fseek/ftell with fseeko64/ftello64 to enable files over 2GB on 32 bit systems and it will work on 64 bit too. And then the PRIu64 for formatting. Tested this on armhf and it works

**Comment by clbr** [comment]
Applying it a bit differently, but building on 32-bit rpi should become possible. Whether official builds will be made, that's a different question. Thank you for the report.

**Comment by clbr** [comment]
6a2c2c82a1502e
