### ISSUE TITLE
How to made get-screenshot request?

### ISSUE THREAD

**Issue by onlineapps-cloud** [kasmtech/KasmVNC#258]
**Describe the bug**
hi, im trying to understand how to get screenshot using this guide https://www.kasmweb.com/kasmvnc/docs/latest/developer_api.html#get-screenshot

In documentation say: **All API calls require owner credentials.**
but i don't see any example, how i need to made correct request including owner credentials? best regards

**Comment by mmcclaskey** [comment]
More details with an example were added to the wiki at the top.
https://github.com/kasmtech/KasmVNC/wiki/API
