### ISSUE TITLE
Is there any way to disable kasm_user / password in docker image

### ISSUE THREAD

**Issue by yoongeon1206** [kasmtech/KasmVNC#259]
currently, the kasm docker image has a default user and a password. I just try to remove them in dockerfile.
We are looking for a way for developers to easily access KASM without receiving the ID password
It is necessary to delete the ID and password set by default as the first step.
I want to make the developer approach the KASM service without access ID and password.

**Comment by mmcclaskey** [comment]
Sorry, I do not understand the requirement clearly. However, Kasm Workspaces handles authentication and session management and integrates with SSO providers that support OIDC or SAML, but also supports managing users within Kasm Workspaces itself. Kasm Workspaces supports unauthenticated access for end users via Casting Sessions, if you really want to provider unauthenticated access.

KasmVNC by itself does have a username and password, and Kasm Workspaces generates random KasmVNC creds for each Kasm Workspaces session and those are hidden from the user. If you wanted to create something on your own that uses KasmVNC, but without Kasm Workspaces you can. You basically would need to put a proxy in front of your KasmVNC sessions and have that proxy inject the Basic Auth credentials for the users based on your own rules.

As for setting the username and password for a KasmVNC user, see the getting started section. There is a command `vncpasswd` which is a symlink to `kasmvncpasswd`
https://github.com/kasmtech/KasmVNC#getting-started

Here is how we do it in our containers
```bash
echo -e "${VNC_PW}\n${VNC_PW}\n" | kasmvncpasswd -u kasm_user -wo
```

**Comment by ehfd** [comment]
You can create a kasmvncpassword password file, then disable basic authentication. That's probably the answer OP is looking for.

**Comment by Ninofj** [comment]
> You can create a kasmvncpassword password file, then disable basic authentication. That's probably the answer OP is looking for.

Can you explain how to do that?

**Comment by ehfd** [comment]
@Ninofj 

Use the option `-disableBasicAuth` at startup, but still have a generated `$HOME/.kasmpasswd` file from `kasmvncpasswd` with an irrelevant password you will not use.

**Comment by mmcclaskey** [comment]
Closing the issue, disabling basic auth via the -disableBasicAuth is correct. As a note, this is not a supported configuration by us, therefore, it is not an option in the kasmvnc.yaml configuration file, however, vncserver will take additional command line parameters and pass them to Xvnc.
