### ISSUE TITLE
Archcraft proxmox kasmvnc

### ISSUE THREAD

**Issue by sitolam** [kasmtech/KasmVNC#263]
**Describe the bug**
There are weird things happening when I try to use kasmvnc. I set up kasmvnc by installing the aur package: `kasmvncserver-bin` with this `xstartup` file:
```bash
#!/bin/sh

openbox-session
```
Everything sort of works but when I try to run thunar it launches on the display of my proxmox, I can solve this by running it as the superuser but that is not really a fix. Also the dock is not showing in the kasmvnc display but it is displayed on the proxmox display. 
See the video for more info.

**System Description**
Provide the output of 
```bash
cat /etc/os-release
uname -a
```
```bash
NAME="Archcraft"
PRETTY_NAME="Archcraft"
ID=archcraft
ID_LIKE=arch
BUILD_ID=rolling
ANSI_COLOR="38;2;23;147;209"
HOME_URL="https://archcraft.io"
DOCUMENTATION_URL="https://wiki.archcraft.io"
SUPPORT_URL="https://www.reddit.com/r/archcraft"
BUG_REPORT_URL="https://github.com/archcraft-os/archcraft/issues"
PRIVACY_POLICY_URL="https://terms.archlinux.org/docs/privacy-policy/"
LOGO=archcraft
IMAGE_ID=archcraft
IMAGE_VERSION=2024.07.01
``` 
```bash
Linux archcraft 6.10.2-arch1-1 #1 SMP PREEMPT_DYNAMIC Sat, 27 Jul 2024 16:49:55 +0000 x86_64 GNU/Linux
```

**KasmVNC Details**

Provide the output of this command.
```bash
Xvnc -version
```
```bash
zsh: command not found: xvnc
```

**To Reproduce**
Steps to reproduce the behavior (for non-installation issues):
1. Install archcraft with openbox on proxmox
2. Download `kasmvncserver-bin` from the aur
3. Edit the `xstartup` file by replacing the content with `openbox-session`
4. Access the kasmvnc server from kasm workspaces
5. Launch thunar 

**Expected behavior**
I expected that thunar would launch on the kasmvnc display and not on the proxmox display.

**Additional context**
The video:

https://github.com/user-attachments/assets/6c4dd2b7-5a18-49b8-8901-d82b4fa610b6

> The novnc display is the proxmox display

**Comment by mmcclaskey** [comment]
I can likely take a guess at the issue at a high level. There are multiple X sessions running on your system and one of them is managed by Proxmox. I have zero knowledge or experience with Proxmox, but I have general knowledge X. Each VNC session has a corresponding X session and your Desktop Environments and Window managers run on an X session. If you start Thunar and see it open on the wrong VNC session, then you launched Thunar targeting the wrong X session. If you didn't specify one in the command line arguments when launching Thunar, then it made an assumption based on enviornmental variables. There are environmental variables that set your X11 session and if you don't override that, it will use whatever is set there. In either case, KasmVNC is working as expected, this is a system engineering issue, just need to launch Thunar correctly and it will stick to the right X11 session.
