### ISSUE TITLE
screenshot not found

### ISSUE THREAD

**Issue by sahara101** [kasmtech/KasmVNC#265]
**Describe the bug**
I get this error several times:

host: megw
ingest_date: 202408081738
application: session
levelname: ERROR
process: __main__
message
192.168.1.21 POST https /screenshot?width=1000&height=1000 404 NOT FOUND - b'Screenshot not found.'

It seems to me this is one cause why crowdsec is banning my external IP.
**System Description**
Provide the output of 
```bash
cat /etc/os-release
PRETTY_NAME="Debian GNU/Linux 12 (bookworm)"
NAME="Debian GNU/Linux"
VERSION_ID="12"
VERSION="12 (bookworm)"
VERSION_CODENAME=bookworm
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"
uname -a
Linux kasm 6.8.8-4-pve #1 SMP PREEMPT_DYNAMIC PMX 6.8.8-4 (2024-07-26T11:15Z) x86_64 GNU/Linux
```

**KasmVNC Details**
Provide the filename of the package you installed KasmVNC with. The filename includes important details like the OS, architecture, and commit sha.
kasm_release_1.15.0.06fdc8.tar.gz

Provide the output of this command.
```bash
Xvnc -version
-
```

**To Reproduce**
Steps to reproduce the behavior (for non-installation issues):
1. Go to Workspace
2. Click on refresh page because traefik does not always automatically redirect?

**Expected behavior**
No error logs in debug

**Browser**
If this is a problem with the KasmVNC client, provide details about the browser you are accessing KasmVNC from.
 - Chrome
 - Safari

**Additional context**

I also get these errors:

`
host: kasm
ingest_date: 202408081747
application: connection_proxy
levelname: ERROR
message
Request failed with status code 500
{"message":"Request failed with status code 500","name":"AxiosError","stack":"AxiosError: Request failed with status code 500\n    at settle (/gclient/node_modules/axios/dist/node/axios.cjs:1967:12)\n    at IncomingMessage.handleStreamEnd (/gclient/node_modules/axios/dist/node/axios.cjs:3066:11)\n    at IncomingMessage.emit (node:events:525:35)\n    at endReadableNT (node:internal/streams/readable:1358:12)\n    at processTicksAndRejections (node:internal/process/task_queues:83:21)\n    at Axios.request (/gclient/node_modules/axios/dist/node/axios.cjs:3877:41)\n    at runMicrotasks (<anonymous>)\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)\n    at async Object.authorizeGuacSession (/gclient/kasm.js:183:13)\n    at async /gclient/server.js:30:21","config":{"transitional":{"silentJSONParsing":true,"forcedJSONParsing":true,"clarifyTimeoutError":false},"adapter":["xhr","http"],"transformRequest":[null],"transformResponse":[null],"timeout":0,"xsrfCookieName":"XSRF-TOKEN","xsrfHeaderName":"X-XSRF-TOKEN","maxContentLength":-1,"maxBodyLength":-1,"env":{"Blob":null},"headers":{"Accept":"application/json, text/plain, */*","Content-Type":"application/json","User-Agent":"axios/1.6.7","Content-Length":"1179","Accept-Encoding":"gzip, compress, deflate, br"},"httpsAgent":{"_events":{},"_eventsCount":2,"defaultPort":443,"protocol":"https:","options":{"rejectUnauthorized":false,"path":null},"requests":{},"sockets":{},"freeSockets":{},"keepAliveMsecs":1000,"keepAlive":false,"maxSockets":null,"maxFreeSockets":256,"scheduling":"lifo","maxTotalSockets":null,"totalSocketCount":0,"maxCachedSessions":100,"_sessionCache":{"map":{"proxy:443::::::::false:::::::::::::":{"type":"Buffer","data":[48,130,5,71,2,1,1,2,2,3,4,4,2,19,2,4,32,55,155,64,32,84,67,86,250,109,187,163,219,110,113,11,146,201,222,243,219,117,21,171,45,199,73,134,110,113,235,78,91,4,48,62,86,62,95,200,70,97,66,134,69,252,243,35,225,177,253,191,66,201,247,103,173,108,180,252,235,234,162,71,48,153,126,150,175,38,117,138,135,251,249,18,28,185,45,139,122,28,197,161,6,2,4,102,181,4,202,162,4,2,2,28,32,163,130,3,207,48,130,3,203,48,130,2,179,160,3,2,1,2,2,20,57,161,5,193,71,114,137,150,85,68,174,86,217,81,38,201,200,238,127,170,48,13,6,9,42,134,72,134,247,13,1,1,11,5,0,48,117,49,11,48,9,6,3,85,4,6,19,2,85,83,49,11,48,9,6,3,85,4,8,12,2,86,65,49,13,48,11,6,3,85,4,7,12,4,78,111,110,101,49,13,48,11,6,3,85,4,10,12,4,78,111,110,101,49,13,48,11,6,3,85,4,11,12,4,68,111,70,117,49,13,48,11,6,3,85,4,3,12,4,107,97,115,109,49,29,48,27,6,9,42,134,72,134,247,13,1,9,1,22,14,110,111,110,101,64,110,111,110,101,46,110,111,110,101,48,30,23,13,50,52,48,56,48,55,49,57,51,50,50,51,90,23,13,50,57,48,56,48,54,49,57,51,50,50,51,90,48,117,49,11,48,9,6,3,85,4,6,19,2,85,83,49,11,48,9,6,3,85,4,8,12,2,86,65,49,13,48,11,6,3,85,4,7,12,4,78,111,110,101,49,13,48,11,6,3,85,4,10,12,4,78,111,110,101,49,13,48,11,6,3,85,4,11,12,4,68,111,70,117,49,13,48,11,6,3,85,4,3,12,4,107,97,115,109,49,29,48,27,6,9,42,134,72,134,247,13,1,9,1,22,14,110,111,110,101,64,110,111,110,101,46,110,111,110,101,48,130,1,34,48,13,6,9,42,134,72,134,247,13,1,1,1,5,0,3,130,1,15,0,48,130,1,10,2,130,1,1,0,148,148,119,209,44,80,153,157,236,32,192,32,123,2,164,200,159,221,171,122,96,245,69,167,67,192,159,101,169,67,254,219,6,111,227,142,150,111,120,199,83,80,202,42,144,50,102,150,65,110,108,189,67,89,5,217,70,30,13,227,166,132,20,252,81,68,18,127,95,6,70,197,191,150,188,195,95,170,82,75,137,5,116,247,83,85,29,9,200,223,172,15,160,22,26,1,243,125,95,211,183,193,246,74,197,174,62,88,164,173,160,52,149,126,141,66,52,180,109,67,174,254,46,42,197,101,155,98,93,255,4,28,173,134,10,164,0,108,13,49,79,86,203,214,36,145,116,100,230,206,249,31,195,96,68,99,216,98,99,7,93,20,84,93,107,43,226,116,150,98,2,181,75,191,208,227,98,202,253,127,103,236,163,147,23,140,236,99,160,15,150,67,200,94,125,129,60,137,146,102,219,131,237,24,109,84,77,3,180,52,188,101,220,50,175,151,43,35,238,243,149,210,203,143,96,241,201,28,106,74,44,203,48,86,75,163,83,12,215,205,168,97,76,184,44,27,31,102,83,61,82,157,36,53,196,241,2,3,1,0,1,163,83,48,81,48,29,6,3,85,29,14,4,22,4,20,136,134,210,97,233,237,23,223,90,150,91,123,95,105,211,173,245,226,241,79,48,31,6,3,85,29,35,4,24,48,22,128,20,136,134,210,97,233,237,23,223,90,150,91,123,95,105,211,173,245,226,241,79,48,15,6,3,85,29,19,1,1,255,4,5,48,3,1,1,255,48,13,6,9,42,134,72,134,247,13,1,1,11,5,0,3,130,1,1,0,110,74,11,201,149,149,215,120,18,182,69,46,234,55,16,175,17,41,240,135,112,234,233,141,157,215,118,47,93,23,30,184,69,126,55,255,0,22,20,229,172,143,50,145,162,223,88,34,16,197,51,249,68,111,230,10,84,32,137,69,126,187,2,59,30,2,186,132,215,174,164,116,18,218,182,28,34,245,199,58,130,188,47,131,178,111,179,129,245,172,217,219,155,247,104,63,77,238,142,9,77,132,26,104,241,135,181,97,32,247,24,188,0,151,104,198,146,133,88,255,24,221,32,121,220,72,192,98,157,206,82,149,117,202,169,31,49,116,136,4,83,165,73,5,44,217,105,214,240,134,99,188,158,167,210,8,10,240,229,59,137,1,247,28,63,39,255,133,58,205,75,192,88,49,103,61,192,234,184,23,126,209,73,60,184,137,170,166,179,78,100,50,181,88,26,217,25,45,223,20,11,27,190,190,15,43,228,241,250,181,148,242,234,73,104,213,178,242,8,148,139,238,44,127,236,215,101,42,134,126,68,25,74,187,125,125,39,179,10,244,247,7,115,128,125,32,152,70,206,132,19,244,71,204,202,81,164,2,4,0,165,3,2,1,18,166,7,4,5,112,114,111,120,121,169,4,2,2,1,36,170,129,227,4,129,224,63,219,158,235,176,151,75,45,159,1,148,197,26,85,86,12,32,62,144,177,242,48,216,204,191,5,51,39,96,207,164,122,30,73,6,76,214,131,183,157,200,134,243,205,143,23,101,79,37,44,10,118,242,97,107,96,93,52,242,164,231,222,171,32,19,253,48,79,204,214,26,162,50,36,223,178,74,109,30,178,228,100,24,178,140,159,164,178,113,160,26,16,56,164,163,167,165,25,211,3,208,141,83,103,171,104,158,183,190,70,197,5,51,236,10,104,43,57,212,0,124,48,167,170,176,130,81,33,99,225,93,27,252,86,89,42,165,186,44,33,215,254,131,0,113,223,119,42,141,158,132,248,55,128,229,225,110,151,180,238,250,89,5,41,18,251,157,83,173,214,118,149,237,62,213,115,26,196,53,116,239,33,88,127,49,31,134,145,71,198,15,253,176,174,185,174,33,24,106,252,186,228,203,171,116,210,199,54,31,191,101,206,91,53,23,231,216,238,152,79,212,127,22,103,174,7,2,5,0,191,215,212,65]}},"list":["proxy:443::::::::false:::::::::::::"]}},"method":"post","url":"https://proxy:443/api/guac_auth","data":"{\"username\":\"admin@kasm.local\",\"token\":\"eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJzZXNzaW9uX3Rva2VuX2lkIjoiNWE1NTAzYTAtNTVjMS00NzI0LWE0MzEtNTg0N2UxMjhmMjk1IiwiYXV0aG9yaXphdGlvbnMiOlsxMDAsMjAwXSwiZXhwIjoxNzIzNDI3MDMzfQ.lzKkgEduLLCzOFD6JbApF4uyHI5bIkjTQ8L-m1yfO8LXqCVlqkj6cDRsluDmIXz0Y2t9_VZSfbFHBQTFU30yj9Q4liqrKSQsOUAbuIPiWL-XfaMKhbPwmiJnsE01a2XsZsnIJ8p2-aTyUmNeKKl1GSLnpNS32RAUXLOENULqjiCZ2eGDqiv0tugixeH4yVqW8Sbxyusbo4Ev806Kp99elw9rHMBGa00roQLzzX4nEivUJ2hkmARvZpNx2RxO8QuV7onj7fn8A9puDgd-t-QGq-rv3e687iznTQMgUry3iWlq1rdStVw2uKSxR_GdrRy248YIrvE4_PRxIPef1GLW0g\",\"kasm_id\":\"1f87a82a92a749bd9c0a1610766663b8\",\"kasm_client_key\":\"\",\"service\":\"kasm_guac\",\"auth_token\":\"eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJjb25uZWN0aW9uX3Byb3h5X2lkIjoiNDUwNjNmNDEtMzg5MS00ZTVhLTk4NjMtMzdlMzcwODA4MmFlIiwiZXhwIjoxNzU0NTk2OTAzLCJhdXRob3JpemF0aW9ucyI6WzgwXX0.Zj6irc5_yUDQDFMka6_uQyksFgZdArOV9QiSKQqLcu6deTDl7Qsdj5fiD8DA0XjA5nb8JXWHKZQz4GOO-QOR4gM7I5y7gM77dPZN-MYUIg60zYD6fh0ptK4U1Nmvg-E7nkCIyjLvtBR_eu8uBXaz_I-FI-Z0aeQqrlIWgrBFluEh-voPcMXhKm-lL3fWlOHOOTQ_MdJGKEl8XvhSeuIxmt-B2t5659EwHROplF2HgWqrB9eVcub7ygWwYtBPxS59INpS5K9utqEovwlvDcCfC1WpPXKZhTD5S0i4Kvod4xPy1p9reyRwK8tjBlujhQ5jtn3SEBPrwnXuOG6YE3hvbQ\"}"},"code":"ERR_BAD_RESPONSE","status":500}
AxiosError: Request failed with status code 500
    at settle (/gclient/node_modules/axios/dist/node/axios.cjs:1967:12)
    at IncomingMessage.handleStreamEnd (/gclient/node_modules/axios/dist/node/axios.cjs:3066:11)
    at IncomingMessage.emit (node:events:525:35)
    at endReadableNT (node:internal/streams/readable:1358:12)
    at processTicksAndRejections (node:internal/process/task_queues:83:21)
    at Axios.request (/gclient/node_modules/axios/dist/node/axios.cjs:3877:41)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Object.authorizeGuacSession (/gclient/kasm.js:183:13)
    at async /gclient/server.js:30:21
`
    
`host: kasm
ingest_date: 202408081747
application: kasm_api
levelname: ERROR
kasm_user_name: admin@kasm.local
process: cherrypy.error.124589764428320
client_ip: 172.18.0.3
user_agent: axios/1.6.7
message
[08/Aug/2024:17:47:54] HTTP 
Traceback (most recent call last):
  File "cherrypy/_cprequest.py", line 628, in respond
  File "cherrypy/_cprequest.py", line 687, in _do_respond
  File "cherrypy/lib/encoding.py", line 219, in __call__
  File "cherrypy/lib/jsontools.py", line 59, in json_handler
  File "cherrypy/_cpdispatch.py", line 54, in __call__
  File "utils.py", line 321, in new_func
  File "client_api.py", line 2675, in guac_auth
  File "data/access_postgres.py", line 840, in updateKasm
  File "data/access_postgres.py", line 5233, in _save
  File "data/access_postgres.py", line 5230, in _save
  File "sqlalchemy/orm/session.py", line 1026, in commit
  File "sqlalchemy/orm/session.py", line 493, in commit
  File "sqlalchemy/orm/session.py", line 472, in _prepare_impl
  File "sqlalchemy/orm/session.py", line 2451, in flush
  File "sqlalchemy/orm/session.py", line 2589, in _flush
  File "sqlalchemy/util/langhelpers.py", line 68, in __exit__
  File "sqlalchemy/util/compat.py", line 129, in reraise
  File "sqlalchemy/orm/session.py", line 2549, in _flush
  File "sqlalchemy/orm/unitofwork.py", line 422, in execute
  File "sqlalchemy/orm/unitofwork.py", line 586, in execute
  File "sqlalchemy/orm/persistence.py", line 230, in save_obj
  File "sqlalchemy/orm/persistence.py", line 1008, in _emit_update_statements
sqlalchemy.orm.exc.StaleDataError: UPDATE statement on table 'kasms' expected to update 1 row(s); 0 were matched.
`    

Thank you!

**Comment by mmcclaskey** [comment]
Getting 404 errors for the screenshot API is fairly normal in the full Workspaces. Its due to race conditions, like a user going to their dashboard just when a session is deleted for any reason. 

The other two errors you posted are not related.

The SQL error about an UPDATE statement on the kasms table is a known issue that are tracking, however, there are no known negative consequences from that issue.

I don't have enough context around the last error message to provide any response.

But none of these errors have anything to do with your public IP address getting banned on websites or services.
