### ISSUE TITLE
KasmVNC is not getting pre created .kasmpasswd

### ISSUE THREAD

**Issue by prasad89** [kasmtech/KasmVNC#273]
**Describe the bug**
I'm creating `.kasmpasswd` by 
`echo -e "$UUID\n$UUID\n" | kasmvncpasswd -u $USER -rwo /tmp/.kasmpasswd`
I'm expecting after running `vncserver -select-de mate` 
It should not prompt to create user again but that's not the case.
Also I tried passing `-PasswordFile /tmp/.kasmpasswd` in `vncserver`
Also in yaml I'm pointing to `kasm_password_file: /tmp/.kasmpasswd`

**System Description**
Provide the output of 
```bash
cat /etc/os-release
PRETTY_NAME="Ubuntu 24.04 LTS"
NAME="Ubuntu"
VERSION_ID="24.04"
VERSION="24.04 LTS (Noble Numbat)"
VERSION_CODENAME=noble
ID=ubuntu
ID_LIKE=debian
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
UBUNTU_CODENAME=noble
LOGO=ubuntu-logo

uname -a
Linux 4daa0606fd3f 6.8.0-41-generic #41-Ubuntu SMP PREEMPT_DYNAMIC Fri Aug  2 20:41:06 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by prasad89** [comment]
Can you please provide me commands for 
create password before hand so server should not prompt for anything

**Comment by Ninofj** [comment]
Did you find a way to create the file beforehand?
