### ISSUE TITLE
Audio enabled by default on web

### ISSUE THREAD

**Issue by Manan006** [kasmtech/KasmVNC#277]
Hey, sorry if I was not supposed to make an issue here, I could not find any other methods.

I'm trying to have the sound/audio be enabled by default when opening the page on web. But I can't find it anywhere in the docs.
![image](https://github.com/user-attachments/assets/82df3593-8f8a-41b9-bc0f-d3cb02916f8a)

Am I missing something or this is not possible?

**Comment by mmcclaskey** [comment]
KasmVNC does not support audio. Kasm Workspaces does, but that is handled through channels outside of KasmVNC
