### ISSUE TITLE
API handler for getting a screenshot

### ISSUE THREAD

**Issue by kasmtech** [kasmtech/KasmVNC#28]
@clbr 

Add an API handler on the KasmVNC webserver at /api/get_screenshot. The path should take the following arguments. The api will return a screenshot of the current screen as a JPEG image. Use progressive bilinear scaling when the requested resolution is smaller than actual. Cap the resolution at actual for maximum size. Owner permissions are required to make this API call.

width - default to actual
height - default to actual
quality - default to 7, scale is 0 to 9 jpeg quality
deduplicate (true|false) - Default to false. Cache the last requested screenshot. If deduplicate is set to false, the parameters were the same as the last request, and the screen has not been updated since the last request, just resend the cached image. If deduplicate is set to true, the parameters were the same as the last request, and the screen has not been updated since the last request, then return a hash of the cached image. This allows the requester to store the hash instead of the actual image and save processing and bandwidth depending on the use case.

**Comment by clbr** [comment]
I've now pushed this to the api branch. I used the included xxhash
instead of sha256, it should be faster in addition to already being in
the codebase.

**Comment by clbr** [comment]
Details on the hash, since it involves the DB design/etc. xxhash may not be easily available to JS etc, but it doesn't have to be. Whenever a hash is sent, add it as the unique identifier or extra data of the previous fetched image. It's not necessary to recompute hashes on the client side.

**Comment by ledestin** [comment]
I've tested `get_screenshot` and tested width, heigth, quality, deduplicate.

It mostly works, here are caveats:
* Was getting `400 Bad Request` in Insomnia (API tester better than Postman). Log said `Invalid params to screenshot`, but the real reason was that I wasn't logged in in the browser.
* If the user isn't an owner, I got `404 Not Found`.

**Comment by clbr** [comment]
> * Was getting `400 Bad Request` in Insomnia (API tester better than Postman). Log said `Invalid params to screenshot`, but the real reason was that I wasn't logged in in the browser.

The screenshot is also deferred; it's only updated when otherwise doing
VNC work. This is more efficient. If you've never viewed the screen,
there is no screenshot data.

> * If the user isn't an owner, I got `404 Not Found`.

This is secure design. Unauthorized remote users shouldn't be able to
discover what functionality exists for authorized ones.

**Comment by ledestin** [comment]
>> Was getting `400 Bad Request` in Insomnia (API tester better than Postman). Log said `Invalid params to screenshot`, but the real reason was that I wasn't logged in in the browser.

> The screenshot is also deferred; it's only updated when otherwise doing VNC work. This is more efficient. If you've never viewed the screen, there is no screenshot data.

It could be indicated in the error message. I tried a variety of arguments to figure out what was wrong, because the error message implied that params were invalid.

**Comment by kasmtech** [comment]
@clbr, for unauthorized API calls, I think we should return a 401 Unauthroized. For KasmVNC, it is open source and poeple will know the API exists. For Kasm Server, I think we could implement obfuscation of error messages at the top level NGINX servers if they wanted to change 403/401 messages to 404. 

For the 400 bad request. I would think the server side (KasmVNC) would check if the user is authorized prior to checking for the existence of the file and therefore return a 401 or 403 before being able to return a 404. The fact that it returns a 404 implies that authentication was successful.

**Comment by clbr** [comment]
How about returning 401 unauthorized for the entire /api/ space, if the
user is not an owner? That way there is no info leaked about api
existence, but it's still a more clear error page.

**Comment by clbr** [comment]
> It could be indicated in the error message. I tried a variety of arguments to figure out what was wrong, because the error message implied that params were invalid.

Adding an error msg for this.

**Comment by kasmtech** [comment]
> How about returning 401 unauthorized for the entire /api/ space, if the user is not an owner? That way there is no info leaked about api existence, but it's still a more clear error page.

That will work now. When and if we decide to implement differentiated permissions for API calls we can change at that point.

**Comment by clbr** [comment]
Pushed.
