### ISSUE TITLE
RPM assets in 1.3.2 release are named "1.2.0"

### ISSUE THREAD

**Issue by stdweird** [kasmtech/KasmVNC#280]
**Describe the bug**
Downloading the release assets from github for the 1.3.2 release for oracle 8 and 9 x86_64 give
```
[ Downloads]$ rpm -q --info -p kasmvncserver_oracle_8_1.3.2_x86_64.rpm | head
Name        : kasmvncserver
Version     : 1.2.0
Release     : 1.el8
Architecture: x86_64
Install Date: (not installed)
Group       : Unspecified
Size        : 12420090
License     : GPLv2+
Signature   : (none)
Source RPM  : kasmvncserver-1.2.0-1.el8.src.rpm
```

**Installation Details**
This produces a version that is considered older then 1.3.1, and thus won't upgrade

**Comment by mmcclaskey** [comment]
I have a new build with the proper versions, however, I have troubles installing on Oracle 8. I did install oracle-epel-release-el8... any ideas? Below is a link to the fixed build. As soon as I we can validate the new builds are fixed we will update the official releases.

```bash
sudo dnf install perl-Hash-Merge-Simple
Last metadata expiration check: 0:01:35 ago on Tue 24 Sep 2024 06:06:31 PM GMT.
No match for argument: perl-Hash-Merge-Simple
Error: Unable to find a match: perl-Hash-Merge-Simple
```

https://kasmweb-build-artifacts.s3.amazonaws.com/kasmvnc/c46ec688770db92f49fa550b449c5ca757e40ae2/kasmvncserver_oracle_8_1.3.3_feature_KASM-6531_bump_package_versions_c46ec6_x86_64.rpm

**Comment by stdweird** [comment]
odd. i just tried the rpm on a RHEL8 host, it finds the `perl-Hash-Merge-Simple-0.051-15.el8.noarch` from epel just fine.

is installing the epel rpm enough to also enable the repo? (`dnf repolist --enabled` should show it)

perhaps do `dnf clean all` first? 
or use the upstream epel repo rpm `dnf install https://dl.fedoraproject.org/pub/epel/epel-release-latest-8.noarch.rpm`? (not sure it's different from the oracle one)

**Comment by UnixxSH** [comment]
Same problem here on Fedora Workstation 40:

`rpm -q --info -p kasmvncserver_fedora_forty_1.3.2_x86_64.rpm

Name        : kasmvncserver
Version     : 1.2.0
Release     : 1.fc40
Architecture: x86_64
Install Date: (not installed)
Group       : Unspecified
Size        : 12118179
License     : GPLv2+
Signature   : (none)
Source RPM  : kasmvncserver-1.2.0-1.fc40.src.rpm
Build Date  : Wed 28 Aug 2024 02:54:10 PM CEST
Build Host  : b685e6791035
URL         : https://github.com/kasmtech/KasmVNC
Summary     : VNC server accessible from a web browser
Description : ...`

**Comment by wardwouts** [comment]
Same for debian

**Comment by mmcclaskey** [comment]
All packages have been re-published with the correct version numbers and release notes.
