### ISSUE TITLE
Update vncpasswd manual page

### ISSUE THREAD

**Issue by ledestin** [kasmtech/KasmVNC#30]
>The password must be at least six characters long (unless the  -f  com‐
       mand-line option is used-- see below), and only the first eight charac‐
       ters are significant.  Note that the stored password is  not  encrypted
       securely  -  anyone  who has access to this file can trivially find out
       the plain-text password, so vncpasswd always sets  appropriate  permis‐
       sions  (read  and  write only by the owner.)  However, when accessing a
       VNC desktop, a challenge-response mechanism is used over the wire  mak‐
       ing  it hard for anyone to crack the password simply by snooping on the
       network.

@clbr is man page outdated regarding the above? (disregard -f).

**Comment by clbr** [comment]
There is currently no man page for kasmvncpasswd. That page is probably
current for the older/unused here vncpasswd.

kasmvncpasswd stores passwords in salted, encrypted form. The
allowed length is 6-128.

**Comment by ledestin** [comment]
I've updated the man page to be current with the latest changes. Thanks.
