### ISSUE TITLE
Audio Support

### ISSUE THREAD

**Issue by frakman1** [kasmtech/KasmVNC#31]
Is audio supported through a KasmVNC noVNC web page?

**Comment by mmcclaskey** [comment]
No, KasmVNC does not support audio at this time. Kasm Server (
www.kasmweb.com) does support audio in and out, while it is a commercial
product, the free version allows you to create up to 5 concurrent desktops.
It also has many other benefits, I would recommend downloading it and
giving it a try.

**Comment by bi1012037** [comment]
For the part where KasmVNC has no audio, you can use FFmpeg to push the audio yourself. After setting up your own SRS server, use WHIP/WHEP to transmit the audio stream, and then add an <audio> tag on the frontend to receive it—this will enable audio playback.
/usr/share/kasmvnc/www/index.html
The modified video:[https://streamable.com/e/3l3vtk](https://streamable.com/e/3l3vtk)
