### ISSUE TITLE
500 error through Cloudflare Tunnel

### ISSUE THREAD

**Issue by altano** [kasmtech/KasmVNC#38]
I'm trying to tunnel Kasm through a [Cloudflare Tunnel](https://www.cloudflare.com/products/tunnel/) so I can access control it with Cloudflare Access / Cloudflare for Teams. Proxying the web GUI through Cloudflare Tunnel seems to work fine but I can't connect to the sessions. It looks like the VNC web requests are failing with a 500 error, with this request URL:

```
GET https://kasm.norbauer.net/desktop/c50cd3af-cbf9-4144-8896-d70c73cb5f28/vnc/vnc.html?video_quality=2&enable_webp=false&idle_disconnect=20&password=&autoconnect=1&path=desktop/c50cd3af-cbf9-4144-8896-d70c73cb5f28/vnc/websockify&cursor=true&resize=remote&clipboard_up=false&clipboard_down=false&clipboard_seamless=false&toggle_control_panel=false
```

Is there some debug logging I could look at to see why these requests are failing?

**Comment by j-travis** [comment]
Thank you for reporting this issue.

### 500 Errors
Assuming you are using this with Kasm Workspaces, I believe your 500 issue is with Zone settings. Ensure the upstream auth points to the private IP of your Kasm server, and that the Proxy Port is 443 since you are going over cloudflare.

However even once you get past the sessions will fail to connect.

### KasmVNC Websocket Error

It looks like there is a issue establishing the websocket connection for KasmVNC. It should be noted that the websocket connection for Audio works when running through Workspaces.

This issue can be observed without using full Kasm Workspace and instead pointing Cloudflare + Argo Tunnel directly at a one of the containers running KasmVNC.

```
sudo docker run --rm  -it --shm-size=512m -p 6901:6901 -e VNC_PW=password -e VNCOPTIONS="-PreferBandwidth -DynamicQualityMin=4 -DynamicQualityMax=7 -log *:stderr:100"  kasmweb/ubuntu-bionic-desktop:1.9.0
```

The logs from the session. The gap  is the period of time between the container being initialized and then the browser making the request

```
sudo docker run --rm  -it --shm-size=512m -p 6901:6901 -e VNC_PW=password -e VNCOPTIONS="-PreferBandwidth -DynamicQualityMin=4 -DynamicQualityMax=7 -Log *:stderr:100"  kasmweb/ubuntu-bionic-desktop:1.9.0
+ DEFAULT_PROFILE_HOME=/home/kasm-default-profile
+ PROFILE_SYNC_DIR=/kasm_profile_sync
+ '[' -f /home/kasm-user/.bashrc ']'
+ echo 'Profile Sync Directory Does Not Exist. No Sync will occur'
Profile Sync Directory Does Not Exist. No Sync will occur
+ copy_default_profile_to_home
+ echo 'Copying default profile to home directory'
Copying default profile to home directory
+ cp -rp /home/kasm-default-profile/. /home/kasm-user/
+ ls -la /home/kasm-user
total 40
drwxrwxrwx 1 1000 root 4096 Jun 14 19:55 .
drwxr-xr-x 1 root root 4096 Jun 12 10:44 ..
-rw-rw-rw- 1 1000 root   43 Jun 12 10:44 .bashrc
drwxrwxrwx 3 1000 root 4096 Jun 14 19:48 .cache
drwxrwxrwx 3 1000 root 4096 Jun 12 10:43 .config
drwxrwxrwx 2 1000 root 4096 Jun 14 19:55 Desktop
drwxrwxrwx 3 1000 root 4096 Jun 14 19:48 .mozilla
drwxrwxrwx 3 1000 root 4096 Jun 12 10:44 .pki
-rw-rw-rw- 1 1000 root  312 Jun 14 19:55 .wget-hsts
+ verify_profile_config
+ echo 'Verifying Uploads/Downloads Configurations'
Verifying Uploads/Downloads Configurations
+ mkdir -p /home/kasm-user/Uploads
+ '[' -d /home/kasm-user/Desktop/Uploads ']'
+ echo 'Creating Uploads Desktop Symlink'
Creating Uploads Desktop Symlink
+ ln -sf /home/kasm-user/Uploads /home/kasm-user/Desktop/Uploads
+ mkdir -p /home/kasm-user/Downloads
+ '[' -d /home/kasm-user/Desktop/Downloads ']'
+ echo 'Creating Download Desktop Symlink'
Creating Download Desktop Symlink
+ ln -sf /home/kasm-user/Downloads /home/kasm-user/Desktop/Downloads
+ '[' -d /usr/share/kasmvnc/Downloads/Downloads ']'
+ echo 'Creating Downloads RX Symlink'
Creating Downloads RX Symlink
+ ln -sf /home/kasm-user/Downloads /usr/share/kasmvnc/www/Downloads/Downloads
+ ls -la /home/kasm-user/Desktop
total 92
drwxrwxrwx 2 1000 root 4096 Jun 28 15:08 .
drwxrwxrwx 1 1000 root 4096 Jun 28 15:08 ..
-rwxrwxrwx 1 1000 root  570 Jun 14 19:48 code.desktop
-rwxrwxrwx 1 1000 root 5619 Jun 14 19:55 com.obsproject.Studio.desktop
lrwxrwxrwx 1 1000 root   25 Jun 28 15:08 Downloads -> /home/kasm-user/Downloads
-rwxrwxrwx 1 1000 root 9230 Jun 14 19:46 firefox.desktop
-rwxrwxrwx 1 1000 root  954 Jun 14 19:53 gimp.desktop
-rwxrwxrwx 1 1000 root 8515 Jun 14 19:47 google-chrome.desktop
-rwxrwxrwx 1 1000 root 8729 Jun 14 19:50 nextcloud.desktop
-rwxrwxrwx 1 1000 root 3345 Jun 14 19:52 onlyoffice-desktopeditors.desktop
-rwxrwxrwx 1 1000 root 5789 Jun 14 19:50 org.remmina.Remmina.desktop
-rwxrwxrwx 1 1000 root  299 Jun 14 19:53 signal-desktop.desktop
-rwxrwxrwx 1 1000 root  291 Jun 14 19:49 slack.desktop
-rwxrwxrwx 1 1000 root  560 Jun 14 19:48 sublime_text.desktop
-rwxrwxrwx 1 1000 root 1591 Jun 14 19:51 teams.desktop
lrwxrwxrwx 1 1000 root   23 Jun 28 15:08 Uploads -> /home/kasm-user/Uploads
-rwxrwxrwx 1 1000 root  414 Jun 14 19:54 Zoom.desktop
+ rm -rf /home/kasm-user/.config/pulse
+ echo 'Removing Default Profile Directory'
Removing Default Profile Directory
+ rm -rf /home/kasm-default-profile/Desktop
+ /dockerstartup/browser_proxy_config.sh
proxy configs not set
browser_startup_url not set
+ echo -e '\n\n------------------ EXECUTE COMMAND ------------------'


------------------ EXECUTE COMMAND ------------------
+ echo 'Executing command: '\''/dockerstartup/vnc_startup.sh' /dockerstartup/kasm_startup.sh '--tail-log'\'''
Executing command: '/dockerstartup/vnc_startup.sh /dockerstartup/kasm_startup.sh --tail-log'
+ exec /dockerstartup/vnc_startup.sh /dockerstartup/kasm_startup.sh --tail-log
Can't load /home/kasm-user/.rnd into RNG
140710575130432:error:2406F079:random number generator:RAND_load_file:Cannot open file:../crypto/rand/randfile.c:88:Filename=/home/kasm-user/.rnd
Generating a RSA private key
...............................................................+++++
...................................................+++++
writing new private key to '/home/kasm-user/.vnc/self.pem'
-----
xauth:  file /home/kasm-user/.Xauthority does not exist

New '6d753f4fc01e:1 ()' desktop is 6d753f4fc01e:1

Username: default

Creating default startup script /home/kasm-user/.vnc/xstartup
Creating default config /home/kasm-user/.vnc/config
Starting applications specified in /home/kasm-user/.vnc/xstartup
Log file is /home/kasm-user/.vnc/6d753f4fc01e:1.log

start window manager
...

------------------ Xfce4 window manager startup------------------
Skipping XFCE Startup
Starting audio websocket server
Starting audio server
Starting audio service

------------------ Started Audio Out  ----------------------------
Kasm Audio Out PID: 81
Starting audio input server
Starting upload server


------------------ KasmVNC environment started ------------------
Kasm User () started container id 6d753f4fc01e with local IP address 172.17.0.2
Xvnc KasmVNC 0.9 - built May 10 2021 16:27:35
Copyright (C) 1999-2018 KasmVNC Team and many others (see README.me)
See http://kasmweb.com for information on KasmVNC.
Underlying X server release 12010000, The X.Org Foundation

 vncext:      VNC extension running!
 Config:      set immutable AllowOverride
 vncext:      Listening for websocket connections on 0.0.0.0 interface(s), port 6901
 VNCServerST: creating single-threaded server 6d753f4fc01e:1 ()
 vncext:      created VNC server for screen 0
server does not have extension for -dpms option
Listening for incomming MPEG-TS Stream on https://127.0.0.1:8081/<secret>
Awaiting WebSocket connections on wss://127.0.0.1:4901/
 Selection:   Selection owner change for _DBUS_SESSION_BUS_SELECTION_default_65036e8fe9cd43759440c91c5bae3b25
Failed to unload module: Module module-pipe-source not loaded
 * Serving Flask app "kasm_upload_server" (lazy loading)
 * Environment: production
   WARNING: This is a development server. Do not use it in a production deployment.
   Use a production WSGI server instead.
 * Debug mode: off
 * Running on https://0.0.0.0:4902/ (Press CTRL+C to quit)
 Selection:   Selection owner change for _XSETTINGS_S0
 Selection:   Selection owner change for CLIPBOARD_MANAGER
 Selection:   Selection owner change for WM_S0
 Selection:   Selection owner change for XFDESKTOP_SELECTION_0
 Selection:   Selection owner change for _NET_DESKTOP_MANAGER_S0
 Selection:   Selection owner change for XFWM4_COMPOSITING_MANAGER
 Selection:   Selection owner change for _NET_DESKTOP_LAYOUT_S0
 Selection:   Selection owner change for _NET_SYSTEM_TRAY_S0
Stream Connected: ::ffff:127.0.0.1:40914









 websocket 0: got client connection from 192.168.4.44
 websocket 0: using SSL socket
 websocket 0: BasicAuth matched
 websocket 0: using protocol Hixie 75
 websocket 0: connecting to VNC target
 XserverDesktop: new client, sock 28
 EncodeManager: WEBP benchmark result: 33 ms
 Connections: accepted: kasm_user@192.168.4.44_1624892946.11308::websocket
 ```
 
 
 From the client you can observe errors in the developer console and network tab.
 
 ```
  Error during WebSocket handshake: 'Sec-WebSocket-Accept'
 ```
 There are no response headers. 
 
![image](https://user-images.githubusercontent.com/48762190/123662855-d7165a80-d803-11eb-964d-cabb355f5b11.png)


![image](https://user-images.githubusercontent.com/48762190/123661427-86523200-d802-11eb-9522-4056eceee99a.png)

When running through Workspaces and looking at the audio websocket the response headers are present and `Sec-WebSocket-Accept` is present.

This feels like something about the websocket when running through Cloudflare + Argo Tunnel  isnt happy connecting to KasmVNC

**Comment by altano** [comment]
> Assuming you are using this with Kasm Workspaces

Yessir

> I believe your 500 issue is with Zone settings. Ensure the upstream auth points to the private IP of your Kasm server, and that the Proxy Port is 443 since you are going over cloudflare.

Yeah that was correct. Setting my Upstream Auth host to be correct fixed the 500 issue. Now I can more clearly see the `wss` calls failing with a 502. BUT, unlike for you, my audio `wss` also doesn't work.

Just thinking out loud:

* Cloudflare Tunnel _does_ support websockets, fwiw (https://developers.cloudflare.com/cloudflare-one/faq/cloudflare-tunnels-faq#does-cloudflare-tunnel-support-websockets)
* Possibly related?: https://github.com/cloudflare/cloudflared/issues/364
* The tunneled connections are using HTTP3 on the browser end, and are using HTTP1.1 when not tunneling.
* Some images and fonts (e.g. `https://kasm.example.com/desktop/236a7018-1f4d-4295-9da8-fb46505ac0cb/vnc/dist/images/782e6b34fd46a00744786246a454ed11.png`) are giving me 502s as well. When i access them directly in the browser I get a 403.
* Most interesting in your logging of the server side is that there are no errors.

**Comment by altano** [comment]
Actually, the audio web socket works in Chrome but not Firefox. 🤷🏾‍♀️

You were presumably using Chrome when you saw it succeed for you.

**Comment by FumbleNL** [comment]
Hi all, I used Kasm v 1.8.0 behind Cloudflare (in combination with Argo tunnel) for 6 months without any issues, after the upgrade to 1.9.0 it stopped working. I am getting WebSocket failed errors (wss://host/desktop/d80b5cb9-25c2-46aa-a8b7-b3ec644fd28d/vnc/websockify failed). It works fine without Cloudflare. I will try to do some testing to see what is causing this Cloudflare related problem.

**Comment by mmcclaskey** [comment]
@FumbleNL thanks, that helps. 1.8.0 uses an older version of KasmVNC that uses websockify while 1.9.0 uses a later build of KasmVNC that has an embedded websocket/web server. We are working to find the issue and resolve it.

**Comment by mmcclaskey** [comment]
This has been resolved. Cloudflare does not follow the websocket specification precisely. We had to modify the code to ignore the case of the HTTP headers. KasmVNC on the tip of master is fixed. Kasm Workspaces rolling images are updated, so if you just add "-rolling" to the end of the image tag you will get the fix. For example if you were using...

kasmweb/ubuntu-bionic-desktop:1.9.0

Change it to..

kasmweb/ubuntu-bionic-desktop:1.9.0-rolling

Update the image name in the admin panel of Workspaces, go to Images, and edit the desired image. Workspaces will automatically pull images that it does not have, but it will take a few minutes.

The next mainline releases of KasmVNC and Kasm Workspaces will have the fix as well.

**Comment by FumbleNL** [comment]
@mmcclaskey Great news, I just verified your solution and it works. Thank you for your quick response!

**Comment by hobybrenner** [comment]
Same here, I did a quick install at home here, duped a few images to use the rolling ones, and it works great now!  Thank you!

**Comment by Citizen3rased** [comment]
I am having this exact same issue, but with a fresh install of Kasm Workspaces. I'm also seeing websockify calls in my browser. Was websockify added back to KasmVNC again?

**Comment by FumbleNL** [comment]
> I am having this exact same issue, but with a fresh install of Kasm Workspaces. I'm also seeing websockify calls in my browser. Was websockify added back to KasmVNC again? I am not using a reverse proxy. The only containers running are the Kasm docker containers and I'm running on the default 443 port. I have added my server ip as the upstream auth and set 443 as the proxy port.

For my version 1.12.0 works in combination with Cloudflare. In zone config, Upstream Auth Address is my internal IP, Proxy Hostname is the external Cloudflare hostname and Proxy Port is 0 (default config I guess)

**Comment by Citizen3rased** [comment]
@FumbleNL 
Thank you for the reply.. I'm running out of ideas.
You're using the cloudflared tunnel? Or just cloudflared as your DNS provider?
I've been trying to get this to work all week. I really don't understand why it's not working for me. 

What do you mean by 'external Cloudflare hostname'? Do you mean my domain? Like 'kasm.mydomain.net' ?
When I do that, I get an "ERR Name not resolved" instead of the websocket error, and also fails to load session.

What do you have set for "Allow Origin Domain"?

Thank you for your assistance.

**Comment by Citizen3rased** [comment]
I'm running Ubuntu 22.04 Server on baremetal. I did a standard single server installation. It works fine if I access it locally at the internal IP address of the server. The websocket issue only comes up when I use the cloudflared tunnel. 
I followed this tutorial exactly: https://www.youtube.com/watch?v=pv43JiCUlyI
It seems to just work for him, so I'm really scratching my head here.

**Comment by Citizen3rased** [comment]
Wow.. I think I just figured something out. I used one of my other domains just to see if maybe it's a domain setting issue and not a tunnel or kasm issue. It worked! I just don't know why. They are both new domains I haven't changed any settings on, and have no other DNS entries on. They are all through cloudflare.. I'll have to dig into this more. In the meantime I will just use the other domain name.

**Comment by Slopz** [comment]
Same issue with a fresh Kasm install. My domain ends in .cloud if that is of any value.

**Comment by JordyEGNL** [comment]
> > I am having this exact same issue, but with a fresh install of Kasm Workspaces. I'm also seeing websockify calls in my browser. Was websockify added back to KasmVNC again? I am not using a reverse proxy. The only containers running are the Kasm docker containers and I'm running on the default 443 port. I have added my server ip as the upstream auth and set 443 as the proxy port.
> 
> For me version 1.12.0 works in combination with Cloudflare. My zone config settings:
> 
> * Upstream Auth Address is my internal IP
> * Proxy Connections is checked
> * Proxy Hostname is the external Cloudflare hostname
> * Proxy Port is 0 (default config I guess)

When I changed the proxy port to `0` it worked weirdly enough.. I have set my Upstream Auth Address to `proxy`, cannot remeber if I have changed that too... But now everything is working fine
