### ISSUE TITLE
Docker error in goormide

### ISSUE THREAD

**Issue by MegaTKC** [kasmtech/KasmVNC#39]
I started a container on goormide and i am installing kasm server. I just cant seem to do it because of some docker.sock problem. Is there a way to fix this?

Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?

**Comment by mmcclaskey** [comment]
We have not used Goormide, but it looks like a great platform. From what I can see Goormide uses containerization, which means commands you run are already inside a container. That being said, you cannot run the full Kasm Workspaces stack inside a container. You could, however, use KasmVNC. You would have to install KasmVNC inside the container, install a desktop environment, and configure the vnc startup script to start the installed desktop environment. It would be a lot easier to just use one of our Kasm Workspace images, if you could tell Goormide to use a specific docker image for your container.
