### ISSUE TITLE
How to increase the docker Image (Kasm-Desktop deluxe) performance? 

### ISSUE THREAD

**Issue by lucky2719** [kasmtech/KasmVNC#42]
I created a docker container with the Kasm desktop deluxe Image but it looks a bit laggy and slow is their a way to improve the performance? May be any argument to tune the Memory management or something like that?

**Comment by mmcclaskey** [comment]
If you are using the image in the full Kasm Workspaces framework, please use our community edition issue tracker here.. https://bitbucket.org/kasmtech/kasm_release/issues?status=new&status=open

This project is for KasmVNC, which is used within the full Workspaces stack to provide the remote connection to the containerized desktop.

Workspaces is used within large VDI deployments and generally performs very well in comparison to similarly spec'd VDI solutions. The first thing I would check is the memory limit in the image settings under the Images panel under administration. By default is is pretty low, 1768MB, you will hit that pretty quickly and start hitting SWAP which will slow things down pretty good. Next would be the default core count of 1 CPU on the image setting.

After that I would look into the system that it is deployed on. If it is on a cloud provider, what instance type is it deployed on? Digital Ocean shared instance types are hard set to 33% CPU share with no bursting, completely inadequate for a desktop. AWS shared instance types have bursting and will go to 100% for short bursts and generally do ok but will start stalling when playing video. 

If you want to continue the conversation, please open an issue on the community edition tracker link provided. If you are instead talking about slow rendering or frame rate and think the performance issue is related to KasmVNC then please open a new issue here that is more specific to KasmVNC.

**Comment by lucky2719** [comment]
Hey thanks for the reply but then again I wanted to know about the container which I created with respect to Kasm Desktop deluxe /1.9.0 : rolling Image

**Comment by mmcclaskey** [comment]
There is nothing special about that image that would be any different than another image with respect to general performance. There are so many variations of configurations that you could have, I couldn't possibly provide any feedback without any knowledge of your deployment. Are you going through Cloudflare, what type of VM and/or hardware, what software are you launching that you are seeing as being slow, is it the system that is slow or the rendering from the remote system to your browser that is slow.

**Comment by lucky2719** [comment]
Hello thanks for the reply, with respect to configuration I am using it on a  server in which docker is deployed where the configuration is 32Gb Ram and then with the help of the ip address I am using it on my Machine which has 8Gb of ram

Is their any modification that can be done to tune the ram management of Image or to allocate more to the container?

**Comment by mmcclaskey** [comment]
If you are running the image directly using docker run, then all system RAM is available to the container unless you specified parameters to limit it. If you are running the full Kasm Workspaces platform (https://www.kasmweb.com), then you can tweak the RAM and CPU limitations under the Admin panel > Images, click the three dot icon next to the image and select edit. From there you will find all the knobs.

![image](https://user-images.githubusercontent.com/5209269/126331298-5dba3508-5c50-4ea4-8637-f84b2f9694c0.png)

You may find this video useful...

https://youtu.be/teJSUxKEbfE
