### ISSUE TITLE
How to enable  legacy VNC port, and not set vnc login account and password

### ISSUE THREAD

**Issue by qpb8023** [kasmtech/KasmVNC#44]
I want to disable   workspace-core-image  authentication ,I added   vncserver -SecurityTypes None   in vnc_startup.sh,but  Seems invalid

**Comment by mmcclaskey** [comment]
We do not support the legacy VNC port for several reasons. The main reason is that we cannot press forward with improvements with the handcuffs of not being able to break the RFB protocol. At this point, KasmVNC may or may not work with traditional VNC clients but for sure it will not work in the future.
