### ISSUE TITLE
Allow clipboard access to be disabled

### ISSUE THREAD

**Issue by lapnd** [kasmtech/KasmVNC#48]
Hi,
There is a case that the environment need to be isolated and not allow user to copy from the kasm container to local machine.
Is there anyway to configure VNC server to allow one directional copy/paste on clipboard?

**Comment by mmcclaskey** [comment]
See DLP (Data Loss Prevention) features...

https://github.com/kasmtech/KasmVNC/wiki/Data-Loss-Prevention

**Comment by lapnd** [comment]
Thank @mmcclaskey

**Comment by lapnd** [comment]
If I understand correctly, to prevent user copy text from Kasm container to local, it's needed to set -DLP_ClipSendMax=0 on the VNCOPTIONS. I did that already and double check on container
![vnc1](https://user-images.githubusercontent.com/17825933/130235031-e929e40b-e3ca-452a-9d7e-0acf508ea1a5.png)

However, when I did select text on the container, data is still be copied to Clipboard window
![vnc2](https://user-images.githubusercontent.com/17825933/130235145-ffbd6d56-d228-494e-9b6a-de63940501fa.png)

**Comment by mmcclaskey** [comment]
0 disables the DLP. Looks like you need to use the following option to completely disable the clipboard from server to client.

-SendCutText 0

**Comment by lapnd** [comment]
Thank you @mmcclaskey
