### ISSUE TITLE
Vnc server not running

### ISSUE THREAD

**Issue by ns9394551** [kasmtech/KasmVNC#59]

**Comment by ns9394551** [comment]
Help

**Comment by ns9394551** [comment]
![Screenshot_2021-09-28-12-40-31-15_8659c1e795b4b4239e38d87c88c077b3.jpg](https://user-images.githubusercontent.com/91521875/135040090-137f92ca-bbeb-4dad-ae76-43fc87a6c40a.jpg)

**Comment by mmcclaskey** [comment]
KasmVNC is web native, thus it requires no client, you connect to it via a web browser. By default it starts on port 8443, so you would navigate to https://<remote-server-ip>:8443

The legacy VNC port on 5901 is disabled by default and not supported. You can force it to be enabled, however, clients are not guaranteed to work. It will likely work today, but will certainly be broken in the future. We are adding support for binary clipboard, H264 streaming, and other features that simply would not work on a traditional VNC client.
