### ISSUE TITLE
Can not open in macOS,but ok in windows and linux

### ISSUE THREAD

**Issue by jingcheng407** [kasmtech/KasmVNC#65]
![image](https://user-images.githubusercontent.com/7554452/136891495-644f2669-f9bc-4be7-8dd1-5f0a7b63d500.png)
I work in macOS,so can you help me,thank you so much.

docker run --name=ubuntu-bionic-desktop --rm  -it --shm-size=512m -p 8903:6901 -e VNC_PW=password kasmweb/ubuntu-bionic-desktop:1.9.0

https://q.rrrr.run:8903

**Comment by mmcclaskey** [comment]
#37 Please see this issue. I will close this issue, since there is already an open ticket on this. Thank you!
