### ISSUE TITLE
How to install packages with APT in Ubuntu Desktop?

### ISSUE THREAD

**Issue by luisee** [kasmtech/KasmVNC#82]
Hello, I am a beginner in the use of Kasm and I wanted to know how you can use sudo, specifically, to install packages in Ubuntu Desktop, when using sudo it tells me that "sudo" does not exist and when only installing packages like `apt-get install htop` me indicates that I do not have permissions.

The conclusion that I draw is that you can not use sudo or install packages? Can you only use the applications that are installed by default? Thanks for the help.

**Comment by j-travis** [comment]
Hi, this issue is related to Kasm Workspaces and should be posted in the workspaces-issues repo: https://github.com/kasmtech/workspaces-issues

This particular question has been covered.  You can review the issue here:
https://github.com/kasmtech/workspaces-issues/issues/43
