### ISSUE TITLE
mouse not working on remote VM

### ISSUE THREAD

**Issue by connected201** [kasmtech/KasmVNC#83]
Hi, i installed on Debian 11 (Mx linux) KasmVNC
but after connecting to remote VM, mouse not appear on remote screen, how to fix it?
![IPMriTCT68](https://user-images.githubusercontent.com/20506433/148400962-ee81988a-38ef-492a-b5d6-cd9ecf67fcf1.gif)

also, as i understant KasmVNC is an advanced NoVNC version.
i expected to see this:
![image](https://user-images.githubusercontent.com/20506433/148400691-e6f7228d-c5b6-4ed9-a04e-9242358fb881.png)
but i have this:
![image](https://user-images.githubusercontent.com/20506433/148400849-3a4ffaab-8bfa-46b5-ae33-333a01610612.png)

**Comment by mmcclaskey** [comment]
@connected201, the second screenshot is the control panel for Kasm Workspaces platform. When you use KasmVNC by itself, you only get the noVNC control panel. What is your local OS, browser, and browser version?

**Comment by connected201** [comment]
i installed kasmvnc to MX linux https://distrowatch.com/table.php?distribution=mx
Local OS: windows 10
Browser: Mozilla firefox 95.0.2 (64-bit)
Chromium (lVersion 99.0.4810.0 (Developer Build) (64-bit))

**Comment by jimjimovich** [comment]
I'm having the same issue with kasmvnc running on Ubuntu 20.04, connecting from any browser on a different Ubuntu 20.04 machine. I've even tried multiple desktop environments and all have a frozen mouse.

**Comment by pondorondo** [comment]
I can confirm this issue on a current Kali Linux system.

**Comment by mmhdbw** [comment]
> I can confirm this issue on a current Kali Linux system.

Today, I realized, that this was my fault. I did not setup up the password file properly. Using `-w` and `-o` with `kasmpasswd` helped. Alternatively, just add `:wo` in your `~/.kasmpasswd`.

**Comment by mmcclaskey** [comment]
@mmhdbw , thank you for pointing this out. @connected201 @jimjimovich @pondorondo , sorry for letting this ticket slip by. The permissions applied to the user you create is likely giving you read only access to the session. I'm going to create an internal ticket to change vncserver to check for an owner with write permissions and let you know of the issue.

**Comment by mmcclaskey** [comment]
This has been addressed in the latest release.
