### ISSUE TITLE
Kasm credentials not generated?

### ISSUE THREAD

**Issue by remyderuysscher** [kasmtech/KasmVNC#86]
After installing Kasm Workspaces 1.10.0 on Ubuntu server 20.04 LTS  the script finishes but doesn't generate any credentials or start Kasm.

When I reset the admin password this doesn't work either https://www.kasmweb.com/docs/latest/how_to/admin_account_recovery.html

Please help me with getting admin credentials working.

**Comment by j-travis** [comment]
Since this relates to Kasm Workspaces and not KasmVNC, please post the issue over in https://github.com/kasmtech/workspaces-issues/issues
