### ISSUE TITLE
500 Error Cloudflare

### ISSUE THREAD

**Issue by FOREVEREALIZE** [kasmtech/KasmVNC#87]
Hi!
I have set up Kasm Workspaces on my OCI server and every time I create a session and try to connect, it fails a few requests with 500 status code and returns me to the dashboard.

I have tried #38 and all other issues that pop up by searching for cloudflare.
The way i have it set up is: A non-proxied A record on CF and CF Certs on NGINX. 
My zone settings are:

Zone Name: default
Allow Origin Domain: $request_host$
Upsteram Auth Address: 10.0.0.196 (Servers' Private IP)
Load Balance Startegy: Least Load
Search Alternate Zones: ON
Proxy Connections: ON
Proxy Hostname: $request_host$
Proxy Path: desktop
Proxy Port: 443

Any help' would be appreciated!

**Comment by j-travis** [comment]
Hello, since this is related to Workspaces, can you please post over in https://github.com/kasmtech/workspaces-issues

You will want to look through that issue tracker as well to see if this was already covered

**Comment by FOREVEREALIZE** [comment]
Oops
Wrong repo!
