### ISSUE TITLE
BasicAuth allows blank username to view VNC desktop

### ISSUE THREAD

**Issue by magic-commits** [kasmtech/KasmVNC#90]
.kasmpasswd has my username and password along with the :wo and that is the only entry.  However, if you don't enter anything in the username or password field for the BasicAuth prompt, it will open the VNC desktop stream in view-only mode.

Is this intended? If so, how is it possible to disable the BasicAuth that kasmvnc comes with so that I can implement it on my traefik proxy?

In the log below, can see that BasicAuth fails and sends a 401 Unauthorized,  however, it immediately says BasicAuth Matched and then proceeds to setup a view only session.

[kasm.txt](https://github.com/kasmtech/KasmVNC/files/8061927/kasm.txt)

**Comment by mmcclaskey** [comment]
@magic-commits , this is a confirmed bug and has been fixed on master. We are working to release a new version.

**Comment by mmcclaskey** [comment]
This fix was in the 0.9.3 release.
