### ISSUE TITLE
Installation issue

### ISSUE THREAD

**Issue by pauleastus2000** [kasmtech/KasmVNC#92]
I created a debian ARM64 vm instance on google cloud platform. When i try to use the instructions on GitHub The installation never completes. I seems like it installs but it actually dosent install. After support checked they realize the files needed werent installed

**Comment by mmcclaskey** [comment]
@pauleastus2000, while arm support has been added, it has not yet made an official release. We did, however, provide links to arm builds for the public to test with in the mean time. They were posted in the following issue. Please download the appropriate package and install that instead.

https://github.com/kasmtech/KasmVNC/issues/40

**Comment by pauleastus2000** [comment]
ok

**Comment by pauleastus2000** [comment]
can u send me the link here

**Comment by mmcclaskey** [comment]
[https://github.com/kasmtech/KasmVNC/issues/40](https://github.com/kasmtech/KasmVNC/issues/40)
