### ISSUE TITLE
Could it support Chinese input method?

### ISSUE THREAD

**Issue by crazyn2** [kasmtech/KasmVNC#97]
I need a Chinese input method in noVNC of Docker container

**Comment by mmcclaskey** [comment]
You must be reading our minds, we are currently working on this. Expect a week or two before the branch is merged to master and publicly visible. Expect a month or two before we have an official release with IME support.

**Comment by crazyn2** [comment]
Thanks. Looking forward to an official release with IME support.

**Comment by j-travis** [comment]
@crazyn2 ,
We are looking to get some initial feedback with beta testing this feature in the next few days.  If you are interested  , please send us a message here with your email address:
https://kasmweb.com/support.html

**Comment by crazyn2** [comment]
Could you please tell how to get beta version of kasmweb? Or just "docker pull kasmweb/telegram:1.10.0-rolling" get nightly version?

**Comment by crazyn2** [comment]
Could it be enabled in a single docker container like kasmweb/tor-browser

**Comment by j-travis** [comment]
Per the docs linked above, the `:develop` tags of our images are the latest and greatest.

e.g `kasmweb/tor-browser:develop`

There is a menu item for enabled IME in the native KasmVNC control panel as well

**Comment by crazyn2** [comment]
Could it support dark mode of OS?

**Comment by j-travis** [comment]
The Kasm Workspaces app will support a dark mode in the next version, but the individual containers will not automatically change. 
You could of course build a custom image and apply the XFCE and window manager themes you desire.
